//! Behavioral parity tests for the native Bot input boundary
//! (`drogon_core::bots::input`) against the pinned source parsers in
//! `src/main/ipc/bot-schemas.ts`
//! (source revision `c97906287bb7a390b25e2025b600d9fb3c25d9c3`).
//!
//! Root provisionally registered `drogon_core::bots::input` for actual
//! public-library tests; this binds to that real public path (no
//! `#[path]` test-only inclusion).
use drogon_core::bots::input::{self, BotInputError, InvalidInputCategory, parse_bot_create};
use serde::Deserialize;
use serde_json::{Value, json};

/// One entry from `tests/parity/ports/WP-CAP-BOTS/native-input/fixtures/expected.json`,
/// generated by executing the actual pinned source parser (see that
/// directory's README) -- never hand-authored expected values.
#[derive(Deserialize)]
struct Fixture {
    id: String,
    parser: String,
    input: Value,
    expect: String,
    #[serde(default)]
    output: Option<Value>,
}

#[derive(Deserialize)]
struct FixtureFile {
    fixtures: Vec<Fixture>,
}

fn dispatch(fixture: &Fixture) -> Result<Value, BotInputError> {
    match fixture.parser.as_str() {
        "botCreate" => input::parse_bot_create(&fixture.input),
        "botUpdate" => input::parse_bot_update(&fixture.input),
        "botSession" => input::parse_bot_session(&fixture.input),
        "responsibilityCreate" => input::parse_responsibility_create(&fixture.input),
        "botId" => input::parse_bot_id(&fixture.input),
        other => panic!("fixture {}: unknown parser {other}", fixture.id),
    }
}

fn load_fixtures() -> FixtureFile {
    // Embedded at compile time so this test never depends on the process's
    // cwd (never the read-only source checkout, per the migration
    // contract) -- only on this file's own fixed location in the tree.
    const RAW: &str =
        include_str!("../../../tests/parity/ports/WP-CAP-BOTS/native-input/fixtures/expected.json");
    serde_json::from_str(RAW).expect("fixtures/expected.json must be valid JSON")
}

/// Structural equality except for `Number`: two numbers compare equal by
/// numeric value (`as_f64`), not by `serde_json::Number`'s int-vs-float
/// storage kind (a JSON source has no such distinction -- `1` and `1.0`
/// are the same value, but `serde_json::Value::from(1.0_f64) != Value::from(1_u64)`
/// under plain `==`). Still an exact `f64` comparison, so a genuine value
/// difference (precision loss, a wrong magnitude) is never hidden.
fn json_numerically_eq(a: &Value, b: &Value) -> bool {
    match (a, b) {
        (Value::Number(x), Value::Number(y)) => x.as_f64() == y.as_f64(),
        (Value::Array(x), Value::Array(y)) => {
            x.len() == y.len() && x.iter().zip(y).all(|(xi, yi)| json_numerically_eq(xi, yi))
        }
        (Value::Object(x), Value::Object(y)) => {
            x.len() == y.len()
                && x.iter()
                    .all(|(k, v)| y.get(k).is_some_and(|yv| json_numerically_eq(v, yv)))
        }
        _ => a == b,
    }
}

/// The core parity gate: every bounded fixture, generated by actually
/// executing the pinned source parser (see the native-input README),
/// replayed through the native parser. An "accept" fixture requires the
/// native parser to accept *and* produce the same normalized JSON the
/// source produced (compared with `json_numerically_eq`, not raw `==` --
/// see its doc comment); a "reject" fixture requires the native parser to
/// reject too (the specific `BotInputError` category/path is not required
/// to match zod's own issue text -- only the accept/reject boundary and,
/// for accepted cases, the normalized output).
#[test]
fn fixture_battery_matches_source_parser() {
    let file = load_fixtures();
    assert!(
        file.fixtures.len() >= 140,
        "expected a substantial bounded fixture battery, got {}",
        file.fixtures.len()
    );
    let mut accepted = 0usize;
    let mut rejected = 0usize;
    for fixture in &file.fixtures {
        let result = dispatch(fixture);
        match fixture.expect.as_str() {
            "accept" => {
                accepted += 1;
                let value = result.unwrap_or_else(|error| {
                    panic!(
                        "fixture {} ({}): source accepted but native rejected: {error:?}",
                        fixture.id, fixture.parser
                    )
                });
                let expected = fixture.output.as_ref().unwrap_or_else(|| {
                    panic!("fixture {}: accept fixture missing output", fixture.id)
                });
                assert!(
                    json_numerically_eq(&value, expected),
                    "fixture {} ({}): normalized output mismatch: native={value:?} source={expected:?}",
                    fixture.id,
                    fixture.parser
                );
            }
            "reject" => {
                rejected += 1;
                assert!(
                    result.is_err(),
                    "fixture {} ({}): source rejected but native accepted: {:?}",
                    fixture.id,
                    fixture.parser,
                    result.ok()
                );
            }
            other => panic!("fixture {}: unknown expect value {other}", fixture.id),
        }
    }
    // Sanity: the battery actually exercises both boundaries, not just one.
    assert!(
        accepted > 0 && rejected > 0,
        "fixture battery must cover both accept and reject"
    );
}

// --- Original source-test assertions, ported verbatim from
// `bot-schemas.test.ts` (source revision c97906287bb7a390b25e2025b600d9fb3c25d9c3),
// preserved unweakened as their own named tests rather than only folded
// into the data-driven battery above. ---

#[test]
fn source_test_accepts_a_bounded_bot_create_payload_with_harness_default_model_policy() {
    let result = parse_bot_create(&json!({
        "characterPreset": "samwell",
        "displayIdentity": { "displayName": "Archivist", "handle": null, "title": "Researcher" },
        "harnessPolicy": { "defaultHarness": "codex", "explicitModel": null },
        "instructions": "Keep evidence linked.",
        "memories": []
    }))
    .expect("must accept");
    assert_eq!(result["characterPreset"], json!("samwell"));
    assert_eq!(
        result["harnessPolicy"],
        json!({ "defaultHarness": "codex", "explicitModel": null })
    );
}

#[test]
fn source_test_rejects_unsupported_harnesses_and_undeclared_payload_fields() {
    assert!(
        input::parse_bot_session(&json!({
            "sessionId": "session-1",
            "harness": "invented-harness",
            "model": null,
            "startedAt": 1
        }))
        .is_err()
    );
    assert!(
        parse_bot_create(&json!({
            "characterPreset": "none",
            "displayIdentity": { "displayName": "Watcher", "handle": null, "title": null },
            "harnessPolicy": { "defaultHarness": "codex", "explicitModel": null },
            "instructions": "",
            "memories": [],
            "privileged": true
        }))
        .is_err()
    );
    assert!(
        parse_bot_create(&json!({
            "characterPreset": "none",
            "displayIdentity": { "displayName": "Watcher", "handle": null, "title": null },
            "harnessPolicy": { "defaultHarness": "codex", "explicitModel": null },
            "instructions": "",
            "memories": [],
            "responsibilities": [{ "id": "renderer-invented-responsibility" }]
        }))
        .is_err()
    );
}

#[test]
fn source_test_validates_responsibility_trigger_semantics_at_the_ipc_boundary() {
    let result = input::parse_responsibility_create(&json!({
        "name": "Daily watch",
        "instructions": "Inspect the workspace.",
        "kind": "scheduled",
        "schedule": {
            "projectId": "repo-1",
            "workspaceMode": "new_per_run",
            "timezone": "UTC",
            "rrule": "FREQ=DAILY",
            "dtstart": 1
        }
    }))
    .expect("must accept");
    assert_eq!(result["kind"], json!("scheduled"));
    assert_eq!(result["schedule"]["projectId"], json!("repo-1"));

    assert!(
        input::parse_responsibility_create(&json!({
            "name": "Invalid reactive schedule",
            "instructions": "Do not accept mixed trigger semantics.",
            "kind": "reactive",
            "schedule": {
                "projectId": "repo-1",
                "workspaceMode": "new_per_run",
                "timezone": "UTC",
                "rrule": "FREQ=DAILY",
                "dtstart": 1
            }
        }))
        .is_err()
    );
}

// --- Additional bounded assertions on error shape (category/path), which
// the fixture battery deliberately does not check (see its doc comment). ---

#[test]
fn errors_carry_a_stable_category_and_field_path_without_echoing_payload_content() {
    let error = parse_bot_create(&json!({
        "characterPreset": "none",
        "displayIdentity": { "displayName": "Watcher", "handle": null, "title": null },
        "harnessPolicy": { "defaultHarness": "codex", "explicitModel": null },
        "instructions": "top secret credential leak attempt",
        "memories": [],
        "privileged": true
    }))
    .expect_err("must reject");
    assert_eq!(error.category, InvalidInputCategory::UnknownField);
    // Root review: an UnknownField path names only the enclosing object,
    // never the offending key -- see unknown_key_errors_never_echo_the_key
    // below for the dedicated privacy regression.
    assert_eq!(error.path, "");
    // Bounded privacy: the rejected instructions text never appears in the
    // error's Display output or its structured fields.
    let displayed = error.to_string();
    assert!(!displayed.contains("top secret credential leak attempt"));

    let harness_error = input::parse_bot_session(&json!({
        "sessionId": "session-1",
        "harness": "invented-harness",
        "model": null,
        "startedAt": 1
    }))
    .expect_err("must reject");
    assert_eq!(
        harness_error.category,
        InvalidInputCategory::UnsupportedHarness
    );
    assert_eq!(harness_error.path, "harness");

    let cross_field_error = input::parse_responsibility_create(&json!({
        "name": "Invalid reactive schedule",
        "instructions": "x",
        "kind": "reactive",
        "schedule": {
            "projectId": "repo-1",
            "workspaceMode": "new_per_run",
            "timezone": "UTC",
            "rrule": "FREQ=DAILY",
            "dtstart": 1
        }
    }))
    .expect_err("must reject");
    assert_eq!(
        cross_field_error.category,
        InvalidInputCategory::CrossFieldConflict
    );
    assert_eq!(cross_field_error.path, "schedule");

    let range_error = parse_bot_create(&json!({
        "characterPreset": "none",
        "displayIdentity": { "displayName": "Watcher", "handle": null, "title": null },
        "harnessPolicy": { "defaultHarness": "codex", "explicitModel": null },
        "instructions": "",
        "memories": (0..1001).map(|i| json!(format!("m{i}"))).collect::<Vec<_>>()
    }))
    .expect_err("must reject");
    assert_eq!(range_error.category, InvalidInputCategory::OutOfRange);
    assert_eq!(range_error.path, "memories");
}

/// Root review 2026-09-06 16:49 UTC: an unknown key is caller-controlled
/// input; the diagnostic path must never echo it, at any nesting depth,
/// through any of `BotInputError`'s public surfaces (`Debug`, `Display`,
/// `Serialize`).
#[test]
fn unknown_key_errors_never_echo_the_key_itself() {
    const SENSITIVE_KEY: &str = "sk-live-EXTREMELYSECRETVALUE-1234567890";

    let top_level = parse_bot_create(&json!({
        "characterPreset": "none",
        "displayIdentity": { "displayName": "Watcher", "handle": null, "title": null },
        "harnessPolicy": { "defaultHarness": "codex", "explicitModel": null },
        "instructions": "",
        "memories": [],
        SENSITIVE_KEY: "irrelevant value"
    }))
    .expect_err("must reject");
    assert_eq!(top_level.category, InvalidInputCategory::UnknownField);
    assert_eq!(top_level.path, "");

    let nested = parse_bot_create(&json!({
        "characterPreset": "none",
        "displayIdentity": { "displayName": "Watcher", "handle": null, "title": null, SENSITIVE_KEY: true },
        "harnessPolicy": { "defaultHarness": "codex", "explicitModel": null },
        "instructions": "",
        "memories": []
    }))
    .expect_err("must reject");
    assert_eq!(nested.category, InvalidInputCategory::UnknownField);
    assert_eq!(nested.path, "displayIdentity");

    for error in [&top_level, &nested] {
        assert!(!error.path.contains(SENSITIVE_KEY));
        assert!(!format!("{error:?}").contains(SENSITIVE_KEY));
        assert!(!error.to_string().contains(SENSITIVE_KEY));
        assert!(
            !serde_json::to_string(error)
                .unwrap()
                .contains(SENSITIVE_KEY)
        );
    }
}

/// Root review 2026-09-06 16:49 UTC: `str::trim` differs from ECMAScript
/// `String.prototype.trim` (Unicode `White_Space` vs. the JS `WhiteSpace`/
/// `LineTerminator` set). Fixtures generated by executing the actual
/// pinned parser (see `fixtures/expected.json`): U+FEFF is trimmed away;
/// U+0085, U+001C and U+200B are retained (none of the three is JS
/// whitespace, even though U+0085 *is* Unicode `White_Space`).
#[test]
fn trim_uses_the_ecmascript_whitespace_set_not_unicode_white_space() {
    assert_eq!(
        input::parse_bot_id(&json!("\u{feff}abc\u{feff}")).expect("must accept"),
        json!("abc")
    );
    assert_eq!(
        input::parse_bot_id(&json!("\u{85}abc\u{85}")).expect("must accept"),
        json!("\u{85}abc\u{85}")
    );
    assert_eq!(
        input::parse_bot_id(&json!("\u{1c}abc\u{1c}")).expect("must accept"),
        json!("\u{1c}abc\u{1c}")
    );
    assert_eq!(
        input::parse_bot_id(&json!("\u{200b}abc\u{200b}")).expect("must accept"),
        json!("\u{200b}abc\u{200b}")
    );
}

/// Root review 2026-09-06 16:49 UTC: a finite nonnegative timestamp must
/// round-trip exactly, with no invented "safe integer" bound and no
/// saturating cast. Values and expectations executed against the actual
/// pinned parser (see `fixtures/expected.json`'s `bot_session/timestamp_*`
/// entries); `2**64 - 2048`/`2**64`/`2**64 + 4096` are each exactly
/// representable `f64` values one ULP apart at that magnitude, and
/// `Number.MAX_VALUE` is exactly `f64::MAX`.
#[test]
fn timestamps_preserve_exact_finite_nonnegative_source_values() {
    let session = |value: f64| {
        input::parse_bot_session(&json!({
            "sessionId": "s", "harness": "codex", "model": null, "startedAt": value
        }))
        .unwrap_or_else(|error| panic!("must accept {value}: {error:?}"))
    };
    let started_at = |value: f64| {
        session(value)["startedAt"]
            .as_f64()
            .expect("startedAt must be a number")
    };
    assert_eq!(started_at(0.0), 0.0);
    assert_eq!(started_at(0.5), 0.5);
    assert_eq!(started_at(2f64.powi(64) - 2048.0), 2f64.powi(64) - 2048.0);
    assert_eq!(started_at(2f64.powi(64)), 2f64.powi(64));
    assert_eq!(started_at(2f64.powi(64) + 4096.0), 2f64.powi(64) + 4096.0);
    assert_eq!(started_at(f64::MAX), f64::MAX);

    // A reparsed f64 alone can hide a representation-level value change: a
    // saturating `2**64 as u64` cast produces `u64::MAX`, a genuinely
    // different integer, but `u64::MAX as f64` happens to round back up to
    // exactly `2**64` -- the same bit pattern, masking the defect. Check
    // the actual serialized JSON text too, which does not round-trip that
    // coincidence away: `u64::MAX` serializes as `18446744073709551615`,
    // never the source's own `1.8446744073709552e19`-shaped float text.
    let serialized = serde_json::to_string(&session(2f64.powi(64))).expect("serializable");
    assert!(
        !serialized.contains("18446744073709551615"),
        "startedAt must not silently become u64::MAX's digit string: {serialized}"
    );
}

#[test]
fn importing_this_module_has_no_side_effects_beyond_pure_computation() {
    // input.rs is pure (no fs/network/process); this test simply documents
    // and pins that expectation by calling every parser once with a
    // trivially invalid input and confirming only a value is returned.
    assert!(parse_bot_create(&Value::Null).is_err());
    assert!(input::parse_bot_update(&Value::Null).is_err());
    assert!(input::parse_bot_session(&Value::Null).is_err());
    assert!(input::parse_responsibility_create(&Value::Null).is_err());
    assert!(input::parse_bot_id(&Value::Null).is_err());
}
