//! Parity tests for `drogon_core::locale_ordering` (not yet publicly
//! registered by root -- see module doc and
//! `docs/migration/native-locale-ordering.md`) against bounded,
//! source-executed fixtures.
//!
//! The fixtures in
//! `tests/parity/ports/WP-CAP-BOTS/native-state/locale-ordering/node-fixtures.json`
//! were generated by actually running Node24
//! (`/Users/carlos/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/bin/node`)
//! executing `String.prototype.localeCompare()` -- the exact builtin the
//! pinned source calls at
//! `src/main/persistence/loading-store/bot-persistence.ts:47` with no
//! explicit locale/options argument -- from this repository's own cwd. No
//! step used the reference checkout as cwd or read any of its files: the
//! behavior under test is a JS engine builtin, not source-repository code.
//!
//! This is a candidate-vs-source comparison, not a universal parity claim:
//! ICU4X's compiled data (`icu_collator_data` CLDR 48.2.0 / ICU 78.1rc, per
//! `docs/migration/native-locale-ordering.md`) is a materially different
//! dataset build from Node's bundled ICU (78.3 / CLDR 48.0, confirmed live
//! by this test's own recorded `nodeVersion`/`icuVersion` fields), so any
//! divergence found here is reported, not silently patched over by
//! rewriting the fixture to match the candidate.
#![allow(dead_code)]

use drogon_core::locale_ordering::{self, DisplayNameComparator};
use serde::Deserialize;
use std::cmp::Ordering;
use std::collections::BTreeMap;

const RAW_FIXTURES: &str = include_str!(
    "../../../tests/parity/ports/WP-CAP-BOTS/native-state/locale-ordering/node-fixtures.json"
);

#[derive(Deserialize)]
struct Fixtures {
    #[serde(rename = "resolvedDefaultLocale")]
    resolved_default_locale: String,
    #[serde(rename = "nodeVersion")]
    node_version: String,
    #[serde(rename = "icuVersion")]
    icu_version: String,
    cases: BTreeMap<String, BTreeMap<String, Vec<String>>>,
    pairwise: BTreeMap<String, Vec<Pairwise>>,
}

#[derive(Deserialize)]
struct Pairwise {
    a: String,
    b: String,
    sign: i32,
}

fn fixtures() -> Fixtures {
    serde_json::from_str(RAW_FIXTURES).expect("node-fixtures.json must be valid JSON")
}

/// Explicit BCP-47 locales this build actually validates against (mirrors
/// the doc's required coverage: "the observed default plus explicit en-US,
/// es-MX, sv, tr, de and a non-Latin locale"). `"default"` in the fixture
/// file is Node's own resolved-default-locale recording (`en-US` in the
/// environment the fixtures were generated in); we validate it explicitly
/// as `en-US` since this module never guesses a default locale itself (root
/// owns that binding).
const LOCALE_TAGS: &[(&str, &str)] = &[
    ("default", "en-US"),
    ("en-US", "en-US"),
    ("es-MX", "es-MX"),
    ("sv", "sv"),
    ("tr", "tr"),
    ("de", "de"),
    ("ja", "ja"),
];

#[test]
fn fixture_environment_matches_the_recorded_node_version_boundary() {
    let f = fixtures();
    assert_eq!(f.resolved_default_locale, "en-US");
    assert_eq!(f.node_version, "v24.19.0");
    assert_eq!(f.icu_version, "78.3");
}

#[test]
fn an_invalid_locale_tag_is_a_reported_error_not_a_panic_or_binary_fallback() {
    let err = DisplayNameComparator::for_locale("not a bcp47 tag!!").unwrap_err();
    assert!(matches!(
        err,
        locale_ordering::LocaleOrderingError::InvalidLocale { .. }
    ));
}

#[test]
fn sort_by_display_name_stable_preserves_insertion_order_for_equal_names() {
    #[derive(Clone, Debug, PartialEq)]
    struct Item {
        tag: &'static str,
        name: &'static str,
    }
    let mut items = vec![
        Item {
            tag: "first",
            name: "dup",
        },
        Item {
            tag: "second",
            name: "dup",
        },
        Item {
            tag: "third",
            name: "dup",
        },
        Item {
            tag: "fourth-distinct",
            name: "zzz",
        },
    ];
    locale_ordering::sort_by_display_name_stable(&mut items, "en-US", |i| i.name).unwrap();
    let tags: Vec<&str> = items.iter().map(|i| i.tag).collect();
    assert_eq!(tags, vec!["first", "second", "third", "fourth-distinct"]);
}

/// Byte-distinct but canonically equivalent names (`"éclair"` precomposed
/// NFC U+00E9 vs `"e"` + combining acute U+0301 NFD) must compare
/// `Ordering::Equal` under every admitted locale and, fed from UNSORTED
/// input, keep their insertion relative order through the stable sort.
/// This is a stronger tie than the identical-byte `"dup"` case above: the
/// collator must normalize before comparing, not just detect byte equality.
#[test]
fn canonical_equivalent_byte_distinct_names_compare_equal_and_stay_in_insertion_order() {
    let nfc = "\u{00e9}clair";
    let nfd = "e\u{0301}clair";
    assert_ne!(
        nfc.as_bytes(),
        nfd.as_bytes(),
        "the tie case must be byte-distinct, not merely identical"
    );

    for (label, tag) in LOCALE_TAGS {
        let comparator = DisplayNameComparator::for_locale(tag)
            .unwrap_or_else(|e| panic!("locale {tag} must build a collator: {e}"));
        assert_eq!(
            comparator.compare(nfd, nfc),
            Ordering::Equal,
            "NFD vs NFC must be Equal for {label} ({tag})"
        );
        assert_eq!(
            comparator.compare(nfc, nfd),
            Ordering::Equal,
            "comparison must be symmetric for {label} ({tag})"
        );
    }

    // Unsorted input: the tie pair appears out of order relative to distinct
    // names, inserted NFD-first, NFC-second.
    let mut items: Vec<(&str, &str)> = vec![
        ("zzz-distinct", "zzz"),
        ("eclair-nfd", nfd),
        ("apple-distinct", "apple"),
        ("eclair-nfc", nfc),
    ];
    locale_ordering::sort_by_display_name_stable(&mut items, "en-US", |i| i.1).unwrap();
    let tags: Vec<&str> = items.iter().map(|i| i.0).collect();
    assert_eq!(
        tags,
        vec!["apple-distinct", "eclair-nfd", "eclair-nfc", "zzz-distinct"],
        "canonically equivalent ties must keep insertion order (NFD before NFC), \
         with distinct names ordered around them"
    );
}

/// Compares ICU4X whole-list ordering against every recorded source-executed
/// case, for every required locale. Divergences are asserted (reported as
/// hard test failures with the exact case/locale), not silently reconciled.
#[test]
fn icu4x_whole_list_order_matches_source_executed_fixtures_per_locale() {
    let f = fixtures();
    let mut divergences = Vec::new();
    for (case_name, per_locale) in &f.cases {
        // `equal_name_ties`' fixture stores each item's distinguishing
        // *tag*, not the (all-identical) name actually compared, so the
        // fixed-point re-sort below does not apply to it -- it is instead
        // covered directly by `sort_by_display_name_stable_preserves_insertion_order_for_equal_names`.
        if case_name == "equal_name_ties" {
            continue;
        }
        for (label, target_tag) in LOCALE_TAGS {
            let expected = &per_locale[*label];
            let comparator = DisplayNameComparator::for_locale(target_tag)
                .unwrap_or_else(|e| panic!("locale {target_tag} must build a collator: {e}"));
            let mut actual = expected.clone();
            // Re-derive the *input* order for this case from the fixture's
            // own generator inputs is not available here (only the
            // already-sorted output is stored), so we instead verify a
            // fixed-point property: sorting the expected (already node-
            // sorted) order again under ICU4X must reproduce the identical
            // order, which only holds if ICU4X agrees with every adjacent
            // pairwise comparison node made.
            actual.sort_by(|a, b| comparator.compare(a, b));
            if &actual != expected {
                divergences.push(format!(
                    "case={case_name} locale={label} (icu4x tag={target_tag}): expected {expected:?}, icu4x reorders to {actual:?}"
                ));
            }
        }
    }
    assert!(
        divergences.is_empty(),
        "ICU4X/Node locale-order divergences (see docs/migration/native-locale-ordering.md \"Known version boundary\"):\n{}",
        divergences.join("\n")
    );
}

#[test]
fn icu4x_pairwise_sign_matches_source_executed_fixtures_per_locale() {
    let f = fixtures();
    let mut divergences = Vec::new();
    for (label, target_tag) in LOCALE_TAGS {
        let pairs = &f.pairwise[*label];
        let comparator = DisplayNameComparator::for_locale(target_tag).unwrap();
        for p in pairs {
            let actual = comparator.compare(&p.a, &p.b);
            let actual_sign = match actual {
                Ordering::Less => -1,
                Ordering::Equal => 0,
                Ordering::Greater => 1,
            };
            if actual_sign != p.sign {
                divergences.push(format!(
                    "locale={label} (icu4x tag={target_tag}): compare({:?}, {:?}) node_sign={} icu4x_sign={actual_sign}",
                    p.a, p.b, p.sign
                ));
            }
        }
    }
    assert!(
        divergences.is_empty(),
        "ICU4X/Node pairwise sign divergences:\n{}",
        divergences.join("\n")
    );
}
