// Generated by scripts/generate-bundled-skill-guides.mjs. Do not edit.
// MIT Copyright (c) 2026 Lovecast Inc.
// Source: reference config/scripts/generate-bundled-skill-guides.mjs (read-only Orca checkout)

pub struct BundledSkillGuide {
    pub name: &'static str,
    pub description: &'static str,
    pub markdown: &'static str,
    // Why: no current guide has bundled reference documents, so --full is byte-identical for now.
    pub full_markdown: &'static str,
    pub aliases: &'static [&'static str],
}

/// Canonical (sorted-by-name) embedded guide table.
pub const BUNDLED_SKILL_GUIDES: &[BundledSkillGuide] = &[
    BundledSkillGuide {
        name: "drogon-cli",
        description: "Drive Drogon through the public `drogon-cli`: resolve the executable, check status and capabilities, manage workspaces, projects and worktrees, and operate terminals (create, list, send, read, wait, close), the embedded browser pane (open, navigate, snapshot, click, fill, tabs), harness launch, and the optional Mentu recipe environment (status, open). Use for terminal control, lightweight prompts and shell commands. Use the orchestration guide for supervised multi-agent coordination.",
        markdown: include_str!("../../../skill-guides/drogon-cli.md"),
        full_markdown: include_str!("../../../skill-guides/drogon-cli.md"),
        aliases: &[],
    },
    BundledSkillGuide {
        name: "orchestration",
        description: "Use Drogon native orchestration for supervised multi-agent coordination: run and task ownership, worker dispatch, scoped send and check mail, blocking ask and reply flows, and worker_done completion tracking. Use the drogon-cli guide for full ownership handoffs, terminal control and worktree management instead.",
        markdown: include_str!("../../../skill-guides/orchestration.md"),
        full_markdown: include_str!("../../../skill-guides/orchestration.md"),
        aliases: &[],
    },
];
