//! Parity tests for the public, recognition-only Bot harness ID catalog
//! (`drogon_harness::{KNOWN_TUI_AGENT_IDS, is_known_tui_agent}`), pinned
//! against the source's `TuiAgent` union (`src/shared/tui-agent.ts`,
//! source revision `c97906287bb7a390b25e2025b600d9fb3c25d9c3`).
use drogon_harness::{KNOWN_TUI_AGENT_IDS, is_known_tui_agent};
use serde::Deserialize;

#[derive(Deserialize)]
struct Fixture {
    id: String,
    parser: String,
    input: serde_json::Value,
    expect: String,
}

#[derive(Deserialize)]
struct FixtureFile {
    fixtures: Vec<Fixture>,
}

/// Every `defaultHarness` value from a `bot_create/harness_*_accepted`
/// fixture generated by actually executing the pinned parser (never
/// hand-transcribed here) -- see tests/parity/ports/WP-CAP-BOTS/native-input/.
fn source_verified_harness_ids() -> Vec<String> {
    const RAW: &str =
        include_str!("../../../tests/parity/ports/WP-CAP-BOTS/native-input/fixtures/expected.json");
    let file: FixtureFile =
        serde_json::from_str(RAW).expect("fixtures/expected.json must be valid JSON");
    file.fixtures
        .iter()
        .filter(|f| {
            f.parser == "botCreate"
                && f.id.starts_with("bot_create/harness_")
                && f.expect == "accept"
        })
        .map(|f| {
            f.input["harnessPolicy"]["defaultHarness"]
                .as_str()
                .unwrap_or_else(|| panic!("fixture {} missing harnessPolicy.defaultHarness", f.id))
                .to_string()
        })
        .collect()
}

fn sorted(mut v: Vec<&str>) -> Vec<&str> {
    v.sort_unstable();
    v
}

#[test]
fn known_tui_agent_ids_equals_the_source_generated_fixture_set() {
    let verified = source_verified_harness_ids();
    assert_eq!(
        verified.len(),
        36,
        "expected one source-verified accept fixture per known ID"
    );
    assert_eq!(
        sorted(KNOWN_TUI_AGENT_IDS.to_vec()),
        sorted(verified.iter().map(String::as_str).collect()),
        "KNOWN_TUI_AGENT_IDS must equal the actual pinned-parser-accepted harness IDs"
    );
}

#[test]
fn known_tui_agent_ids_has_no_duplicates() {
    let mut ids = KNOWN_TUI_AGENT_IDS.to_vec();
    ids.sort_unstable();
    let mut deduped = ids.clone();
    deduped.dedup();
    assert_eq!(ids, deduped);
}

#[test]
fn every_known_id_is_recognized() {
    for id in KNOWN_TUI_AGENT_IDS {
        assert!(is_known_tui_agent(id), "{id} must be recognized");
    }
}

#[test]
fn an_unknown_plain_id_is_not_recognized() {
    assert!(!is_known_tui_agent("invented-harness"));
    assert!(!is_known_tui_agent(""));
}

/// Unlike a naive plain-object lookup, these must not fall through a
/// prototype chain to a false positive.
#[test]
fn prototype_shaped_keys_are_not_recognized() {
    for key in [
        "__proto__",
        "constructor",
        "prototype",
        "toString",
        "hasOwnProperty",
        "valueOf",
        "__defineGetter__",
    ] {
        assert!(!is_known_tui_agent(key), "{key} must not be recognized");
    }
}

#[test]
fn case_and_whitespace_variants_of_real_ids_are_not_recognized() {
    for variant in [
        "Claude",
        "CLAUDE",
        "CODEX",
        "Codex",
        "Pi",
        "PI",
        " pi",
        "pi ",
        " codex ",
        "Opencode",
        "ANTIGRAVITY",
        "Devin",
        "GROK",
    ] {
        assert!(
            !is_known_tui_agent(variant),
            "{variant} must not be recognized"
        );
    }
}
