//! The main session's Subagent Policy brief (DISHONEST-3): the same seam
//! `bots::context_files` uses for a Bot's identity -- a file every harness
//! (Claude Code, Codex, Pi, OpenCode, Antigravity) already reads on its own
//! at the start of a session in its cwd -- generalized so the Work Graph's
//! Subagent policy (delegate / adversarial) actually reaches the session it
//! describes, instead of living only in `drogon-cli skills get`'s prose,
//! which nothing prompts a session to go read.
//!
//! Unlike a Bot's home (a directory Drogon provisions and owns outright), an
//! ordinary workspace is very often a real project the owner already has an
//! `AGENTS.md`/`CLAUDE.md` in: overwriting either wholesale, the way
//! `bots::context_files` does for a Bot home, would destroy it. Instead this
//! module owns exactly one clearly delimited MANAGED BLOCK inside each file:
//! everything outside the markers is the owner's, read and left untouched;
//! everything inside is regenerated (the whole block is replaced, never
//! appended alongside a stale copy of itself) on every `harness.start`, so a
//! policy can never outlive the toggle that produced it and a repeated
//! launch in the same workspace is idempotent (same policy in, byte-identical
//! file out -- no mtime churn for opening a second tab).
//!
//! A toggle flip is picked up the moment the NEXT session in this workspace
//! opens (this is written before the harness process spawns, at
//! `harness.start`); a session already running keeps whatever brief it
//! already received -- this module is never called again for it.

use std::io;
use std::path::Path;

use drogon_protocol::RpcError;
use drogon_protocol::graph::GraphPolicy;

use crate::error;

use super::store;

pub const AGENTS_FILE_NAME: &str = "AGENTS.md";
pub const CLAUDE_FILE_NAME: &str = "CLAUDE.md";

const BLOCK_BEGIN: &str =
    "<!-- BEGIN DROGON SUBAGENT POLICY (generated at every session start; do not edit by hand) -->";
const BLOCK_END: &str = "<!-- END DROGON SUBAGENT POLICY -->";

/// Reads `workspace_root`'s `.drogon/graph.json` (a workspace nobody has
/// configured a graph for yet reads back the default policy: delegate off,
/// adversarial off, no approved runtimes -- so the brief is always present
/// and always honest, never merely absent) and writes the current Subagent
/// policy into a managed block inside `AGENTS.md`/`CLAUDE.md` at the
/// workspace root, creating either file if it does not exist yet. Returns
/// whether either file actually changed.
pub fn write_session_policy_brief(
    workspace_root: &Path,
    workspace_id: &str,
) -> Result<bool, RpcError> {
    let graph = store::read_graph(workspace_root)?;
    let section = render_policy_section(workspace_id, &graph.intent.policy);
    let agents_changed = upsert_file(&workspace_root.join(AGENTS_FILE_NAME), &section)
        .map_err(|e| error::io_error(format!("cannot write {AGENTS_FILE_NAME}: {e}")))?;
    let claude_changed = upsert_file(&workspace_root.join(CLAUDE_FILE_NAME), &section)
        .map_err(|e| error::io_error(format!("cannot write {CLAUDE_FILE_NAME}: {e}")))?;
    Ok(agents_changed || claude_changed)
}

/// Renders the Subagent Policy section body (no markers): the same
/// discovery-shaped, real-verb prose `skill-guides/drogon-cli.md`'s
/// "Subagent Policy And The Adversarial Loop" section teaches, addressed
/// directly to the session about to open rather than to an agent that has to
/// go find the guide first. Every `drogon-cli ...` verb named here is one
/// that guide documents (checked by this module's own drift tripwire below).
pub fn render_policy_section(workspace_id: &str, policy: &GraphPolicy) -> String {
    let mut out = String::new();
    out.push_str("## Subagent Policy And The Adversarial Loop\n\n");
    out.push_str(&format!(
        "Generated by Drogon fresh at the start of EVERY session in this workspace, from \
         `intent.policy` in `.drogon/graph.json` (`drogon-cli graph read --workspace \
         {workspace_id} --json`). A policy change here takes effect for the NEXT session \
         opened in this workspace; it never rewrites a session already running.\n\n"
    ));
    if policy.delegate {
        out.push_str(&format!(
            "- **Delegate: ON.** Plan and delegate instead of doing the work yourself: write \
             intent nodes for the subtasks with `drogon-cli graph write-intent --workspace \
             {workspace_id} --file graph-intent.json` and let the graph's own execution path \
             run them, rather than doing the work directly in this session.\n"
        ));
    } else {
        out.push_str("- **Delegate: OFF.** Single node: do the work directly in this session.\n");
    }
    if policy.adversarial.enabled {
        out.push_str(&format!(
            "- **Adversarial testing: ON, up to {} cycle(s).** The desktop runs a bounded \
             Adversarial-test / Code-review loop against a finished workflow: an \
             adversarial-test pass that tries to break the work, then an independent \
             code-review pass that fixes confirmed problems and verifies each fix. That loop \
             is desktop-driven, not something to launch by hand -- leave the work in a state \
             with real, runnable checks, since those are what get replayed.\n",
            policy.adversarial.max_iterations
        ));
    } else {
        out.push_str(
            "- **Adversarial testing: OFF.** No automatic adversarial-test / code-review loop \
             runs after this session's work.\n",
        );
    }
    if policy.approved_runtimes.is_empty() {
        out.push_str(
            "- **Approved runtimes:** none configured -- subagent nodes run under the free \
             local `pi` model by default, so this never costs anything.\n",
        );
    } else {
        let listed = policy
            .approved_runtimes
            .iter()
            .map(|runtime| format!("{}/{}", runtime.harness, runtime.model))
            .collect::<Vec<_>>()
            .join(", ");
        out.push_str(&format!(
            "- **Approved runtimes, in failover order:** {listed}. Launch a subagent node \
             through that exact order with `drogon-cli graph run-node-failover --workspace \
             {workspace_id} --node <NODE_ID> --follow`; it tries each approved runtime and \
             only reaches the fallback once every approved runtime has failed. The result \
             names the runtime that actually ran, never a guess.\n"
        ));
    }
    out
}

/// Reads `path` (empty string when it does not exist yet), replaces or
/// appends the managed block, and writes back only when the content actually
/// changed. Atomic per file (temp file + rename), matching
/// `bots::context_files::write_if_changed`, so a reader starting up never
/// observes a half-written file.
fn upsert_file(path: &Path, section: &str) -> io::Result<bool> {
    let existing = std::fs::read_to_string(path).unwrap_or_default();
    let updated = upsert_managed_block(&existing, section);
    if existing == updated {
        return Ok(false);
    }
    let temporary = path.with_extension("md.drogon-tmp");
    std::fs::write(&temporary, &updated)?;
    std::fs::rename(&temporary, path)?;
    Ok(true)
}

/// Replaces an existing managed block in place, or appends a new one
/// separated from any existing content by exactly one blank line. Content
/// outside the markers is never touched.
fn upsert_managed_block(existing: &str, section: &str) -> String {
    let block = format!("{BLOCK_BEGIN}\n{section}\n{BLOCK_END}\n");
    match find_block(existing) {
        Some((start, end)) => {
            let mut result = String::with_capacity(existing.len() + block.len());
            result.push_str(&existing[..start]);
            result.push_str(&block);
            result.push_str(&existing[end..]);
            result
        }
        None => {
            let mut result = existing.to_string();
            if !result.is_empty() {
                while !result.ends_with("\n\n") {
                    result.push('\n');
                }
            }
            result.push_str(&block);
            result
        }
    }
}

/// The byte range `[start, end)` of an existing managed block, `end`
/// extended past one trailing newline right after [`BLOCK_END`] when present
/// so a replace-in-place never accumulates blank lines across repeated
/// launches. `None` when no block exists yet in this file.
fn find_block(existing: &str) -> Option<(usize, usize)> {
    let start = existing.find(BLOCK_BEGIN)?;
    let after_begin = start + BLOCK_BEGIN.len();
    let end_marker = existing[after_begin..].find(BLOCK_END)? + after_begin;
    let mut end = end_marker + BLOCK_END.len();
    if existing[end..].starts_with('\n') {
        end += 1;
    }
    Some((start, end))
}

#[cfg(test)]
mod tests {
    use super::*;
    use drogon_protocol::graph::{GraphAdversarialPolicy, GraphRuntimeRef};

    fn policy_off() -> GraphPolicy {
        GraphPolicy::default()
    }

    fn policy_delegate_on() -> GraphPolicy {
        GraphPolicy {
            delegate: true,
            ..GraphPolicy::default()
        }
    }

    #[test]
    fn delegate_on_names_the_real_write_intent_verb() {
        let rendered = render_policy_section("ws-1", &policy_delegate_on());
        assert!(rendered.contains("Delegate: ON"));
        assert!(
            rendered.contains(
                "drogon-cli graph write-intent --workspace ws-1 --file graph-intent.json"
            )
        );
    }

    #[test]
    fn delegate_off_says_single_node() {
        let rendered = render_policy_section("ws-1", &policy_off());
        assert!(rendered.contains("Delegate: OFF"));
        assert!(rendered.contains("Single node: do the work directly in this session."));
        assert!(!rendered.contains("Delegate: ON"));
    }

    #[test]
    fn adversarial_on_names_the_iteration_count() {
        let policy = GraphPolicy {
            adversarial: GraphAdversarialPolicy {
                enabled: true,
                max_iterations: 4,
            },
            ..GraphPolicy::default()
        };
        let rendered = render_policy_section("ws-1", &policy);
        assert!(rendered.contains("Adversarial testing: ON, up to 4 cycle(s)"));
    }

    #[test]
    fn approved_runtimes_are_listed_in_configured_order() {
        let policy = GraphPolicy {
            approved_runtimes: vec![
                GraphRuntimeRef {
                    harness: "codex".to_string(),
                    model: "gpt-5.3-codex".to_string(),
                },
                GraphRuntimeRef {
                    harness: "opencode".to_string(),
                    model: "claude-sonnet-4".to_string(),
                },
            ],
            ..GraphPolicy::default()
        };
        let rendered = render_policy_section("ws-1", &policy);
        assert!(rendered.contains("codex/gpt-5.3-codex, opencode/claude-sonnet-4"));
        assert!(rendered.contains("drogon-cli graph run-node-failover --workspace ws-1"));
    }

    /// The property this whole module exists to guarantee: every
    /// `drogon-cli ...` verb the generated brief names is one the bundled
    /// guide actually documents, mirroring
    /// `bots::context_files`'s own drift tripwire (#457) so this brief can
    /// never promise a command the binary does not have.
    #[test]
    fn names_only_verbs_the_bundled_guide_documents() {
        let policy = GraphPolicy {
            delegate: true,
            approved_runtimes: vec![GraphRuntimeRef {
                harness: "codex".to_string(),
                model: "gpt-5.3-codex".to_string(),
            }],
            ..GraphPolicy::default()
        };
        let rendered = render_policy_section("ws-1", &policy);
        let guide = std::fs::read_to_string(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../../skill-guides/drogon-cli.md"
        ))
        .expect("bundled drogon-cli guide source beside the crate");
        let collapse =
            |text: &str| -> String { text.split_whitespace().collect::<Vec<_>>().join(" ") };
        let guide_corpus = collapse(&guide);
        let mut checked = 0;
        for span in backticked_spans(&rendered) {
            if !span.starts_with("drogon-cli ") {
                continue;
            }
            let verb_prefix: String = span
                .split_whitespace()
                .take_while(|token| !token.starts_with('-') && !token.starts_with('<'))
                .collect::<Vec<_>>()
                .join(" ");
            assert!(
                guide_corpus.contains(&collapse(&span)) || guide_corpus.contains(&verb_prefix),
                "generated brief names a command the bundled guide does not document: {span:?}"
            );
            checked += 1;
        }
        assert!(
            checked >= 3,
            "expected the real invocation spans to be checked, got {checked}"
        );
    }

    /// Whitespace-collapsed single-backtick spans, mirroring
    /// `bots::context_files`'s own extractor.
    fn backticked_spans(markdown: &str) -> Vec<String> {
        let mut spans = Vec::new();
        let mut rest = markdown;
        while let Some(open) = rest.find('`') {
            let after_open = &rest[open + 1..];
            let Some(close) = after_open.find('`') else {
                break;
            };
            spans.push(
                after_open[..close]
                    .split_whitespace()
                    .collect::<Vec<_>>()
                    .join(" "),
            );
            rest = &after_open[close + 1..];
        }
        spans
    }

    #[test]
    fn upsert_creates_file_with_only_the_managed_block() {
        let rendered = upsert_managed_block("", "BODY");
        assert_eq!(rendered, format!("{BLOCK_BEGIN}\nBODY\n{BLOCK_END}\n"));
    }

    #[test]
    fn upsert_preserves_owner_content_outside_the_block() {
        let existing = "# My Project\n\nReal instructions the owner wrote.\n";
        let first = upsert_managed_block(existing, "BODY V1");
        assert!(first.starts_with(existing));
        assert!(first.contains("BODY V1"));

        // Re-running with different content replaces ONLY the block, never
        // duplicating it and never touching the owner's text above it.
        let second = upsert_managed_block(&first, "BODY V2");
        assert!(second.starts_with(existing));
        assert!(second.contains("BODY V2"));
        assert!(!second.contains("BODY V1"));
        assert_eq!(second.matches(BLOCK_BEGIN).count(), 1);
    }

    #[test]
    fn upsert_with_identical_content_is_byte_identical() {
        let existing = "# My Project\n\nReal instructions.\n";
        let once = upsert_managed_block(existing, "BODY");
        let twice = upsert_managed_block(&once, "BODY");
        assert_eq!(
            once, twice,
            "an identical re-render must not churn the file"
        );
    }

    #[test]
    fn write_session_policy_brief_is_idempotent_and_honest_by_default() {
        let root = tempfile::tempdir().unwrap();
        // No graph.json at all: the default policy (delegate/adversarial
        // off, no approved runtimes) must still be written, honestly.
        let changed = write_session_policy_brief(root.path(), "ws-1").unwrap();
        assert!(changed);
        let agents = std::fs::read_to_string(root.path().join(AGENTS_FILE_NAME)).unwrap();
        assert!(agents.contains("Delegate: OFF"));
        let claude = std::fs::read_to_string(root.path().join(CLAUDE_FILE_NAME)).unwrap();
        assert!(claude.contains("Delegate: OFF"));

        // A second launch with nothing changed on disk must be a no-op.
        let changed_again = write_session_policy_brief(root.path(), "ws-1").unwrap();
        assert!(!changed_again);
    }

    #[test]
    fn write_session_policy_brief_never_touches_the_owners_existing_content() {
        let root = tempfile::tempdir().unwrap();
        std::fs::write(
            root.path().join(AGENTS_FILE_NAME),
            "# Real Project\n\nDo not break the build.\n",
        )
        .unwrap();
        write_session_policy_brief(root.path(), "ws-1").unwrap();
        let agents = std::fs::read_to_string(root.path().join(AGENTS_FILE_NAME)).unwrap();
        assert!(agents.starts_with("# Real Project\n\nDo not break the build.\n"));
        assert!(agents.contains("Subagent Policy"));
    }
}
