//! Bot identity context files (Gap 1, task_926fddc5e769).
//!
//! Why this exists: the Bot's identity, role, standing instructions and
//! memories already live in the daemon (`super::records::Bot`, composed
//! into a prompt by `super::prompt`), but an INTERACTIVE Bot session
//! dispatches NO model turn (task_e7c183ebc637), so nothing ever carried
//! that identity to the harness. The owner opened his Bot "Arya Stark",
//! asked "quien eres?", and got the harness's own self-description
//! ("Soy Claude Code...") because the harness had no reason to be anyone
//! else.
//!
//! The fix is the seam every harness already reads on its own:
//! `AGENTS.md` in the session's working directory. We materialize
//! `AGENTS.md` (the primary, identity-bearing file) and `CLAUDE.md` (a
//! short pointer to `AGENTS.md`, so Claude Code picks up the same identity
//! and the two can never drift) into the Bot's provisioned home. They are
//! REWRITTEN on every session open, so an edit to the Bot's identity is
//! reflected in the next session and a stale file is never left behind.
//!
//! Everything this file tells the Bot about Drogon is deliberately
//! discovery-shaped: the generated text names the commands that PROVE what
//! the CLI can do (`skills list`, `skills get`, `agent-context`,
//! `status`) instead of an invented verb list that could drift from the
//! binary that actually runs the Bot. An `AGENTS.md` that promises a verb
//! the binary does not have is worse than one that says nothing.

use std::path::Path;

use super::records::Bot;

/// The primary harness context file. Written into the Bot home root.
pub const AGENTS_FILE_NAME: &str = "AGENTS.md";
/// Claude Code's own context file: a pointer to [`AGENTS_FILE_NAME`],
/// never a duplicated copy (the two must not be able to drift).
pub const CLAUDE_FILE_NAME: &str = "CLAUDE.md";

/// Renders the Bot's `AGENTS.md`: identity, standing instructions,
/// memories, and the honest, discovery-first account of what the Bot can
/// do inside a Drogon session.
pub fn render_agents_md(bot: &Bot) -> String {
    let name = bot.display_identity.display_name.trim();
    let mut out = String::new();
    out.push_str(&format!("# {name}\n\n"));
    out.push_str(&format!(
        "You are **{name}**, a persistent Drogon Bot. This file is generated by \
         Drogon from your stored Bot identity and is rewritten every time your Bot \
         opens a session, so it is your standing context here: this is who you are \
         in this workspace.\n\n"
    ));
    out.push_str("## Identity\n\n");
    out.push_str(&format!("- Name: {name}\n"));
    if let Some(handle) = &bot.display_identity.handle {
        out.push_str(&format!("- Handle: @{handle}\n"));
    }
    if let Some(title) = &bot.display_identity.title {
        out.push_str(&format!("- Role: {title}\n"));
    }
    out.push('\n');

    out.push_str("## Standing instructions\n\n");
    let instructions = bot.instructions.trim();
    if instructions.is_empty() {
        out.push_str("No standing instructions recorded.\n\n");
    } else {
        out.push_str(instructions);
        out.push_str("\n\n");
    }

    let memories: Vec<&String> = bot
        .memories
        .iter()
        .filter(|memory| !memory.trim().is_empty())
        .collect();
    if !memories.is_empty() {
        out.push_str("## Memories\n\n");
        for memory in memories {
            out.push_str(&format!("- {}\n", memory.trim()));
        }
        out.push('\n');
    }

    out.push_str(SESSION_GUIDANCE);
    out
}

/// Renders the Bot's `CLAUDE.md`. Deliberately short: it points at
/// [`AGENTS_FILE_NAME`] so the identity lives in exactly one place.
pub fn render_claude_md(bot: &Bot) -> String {
    let name = bot.display_identity.display_name.trim();
    format!(
        "# {name}\n\nYour identity, role, standing instructions and memories for this \
         workspace live in `AGENTS.md`, beside this file. Read it and follow it. This \
         file is only a pointer so the two can never drift: Drogon rewrites both \
         whenever this Bot's stored identity changes.\n"
    )
}

/// The frozen Drogon-session guidance block. Kept as a constant (not
/// interpolated) so the tests can assert its exact discovery commands and
/// the text can never depend on per-Bot data.
const SESSION_GUIDANCE: &str = "\
## Staying yourself

The harness running this session (Claude Code, Codex, Pi, OpenCode,
Antigravity) is the tool, not your identity. Answer as the Bot named above, in
the role above, following the standing instructions and memories. Never present
the underlying CLI as who you are, and never invent Drogon paths, capabilities
or results you did not actually observe.

## Working inside Drogon

Drogon launched this session for this Bot in its own isolated Bot home. That
home is this working directory; it is not necessarily the project you are asked
about, so read and act on the project explicitly when the task names one.

Drogon's own CLI is available to you as `drogon-cli` (its exact path is in the
`DROGON_CLI_COMMAND` environment variable when Drogon exported one). Discover
what it actually does instead of guessing a command:

- `drogon-cli status --json` — confirm the daemon is reachable and list the
  capabilities this service advertises.
- `drogon-cli agent-context` — print the machine-readable schema of the whole
  command surface this exact binary accepts (no running daemon needed).
- `drogon-cli skills list` — list the version-matched Drogon skill guides that
  ship inside this binary.
- `drogon-cli skills get --topic drogon-cli` — print the full Drogon CLI guide
  (workspaces, projects, worktrees, terminals, the embedded browser, harness
  launch, and the optional Mentu recipe environment).
- `drogon-cli skills get --topic orchestration` — print the multi-agent
  orchestration guide (run, task, dispatch, ask, check, reply).

Read the matching guide (or `agent-context`) before using a command whose flags
you are not certain of. Do not guess flags, and do not assume a command exists
because it sounds plausible: if the guide and the schema do not list it, it is
not there.

Mentu recipes are OPTIONAL work. Before you tell anyone you made one or can run
one, ask this host whether it really has the Mentu environment —
`drogon-cli mentu status --workspace <ID> --json` answers installed,
not_installed or partially_available from the daemon's own probe — and if you do
write a recipe, `drogon-cli mentu open --workspace <ID> --recipe <ID>` shows it
to the person you are working for. The CLI guide says when a recipe is worth
writing and when a plain answer is the right output.
";

/// Writes both context files into `home`, returning whether either file
/// changed on disk. Writes are atomic per file (temp file + rename) so a
/// reader (a harness starting in `home`) never observes a half-written
/// identity. Existing files are always overwritten: a stale identity is a
/// bug, not a user file to preserve.
pub fn write_bot_context_files(home: &Path, bot: &Bot) -> std::io::Result<bool> {
    let agents = render_agents_md(bot);
    let claude = render_claude_md(bot);
    let agents_changed = write_if_changed(&home.join(AGENTS_FILE_NAME), &agents)?;
    let claude_changed = write_if_changed(&home.join(CLAUDE_FILE_NAME), &claude)?;
    Ok(agents_changed || claude_changed)
}

fn write_if_changed(path: &Path, contents: &str) -> std::io::Result<bool> {
    if let Ok(existing) = std::fs::read_to_string(path)
        && existing == contents
    {
        return Ok(false);
    }
    let temporary = path.with_extension("md.drogon-tmp");
    std::fs::write(&temporary, contents)?;
    std::fs::rename(&temporary, path)?;
    Ok(true)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::bots::records::{DisplayIdentity, HarnessModelPolicy};

    fn bot(name: &str, handle: Option<&str>, title: Option<&str>) -> Bot {
        Bot {
            id: "bot-1".to_string(),
            character_preset: "arya".to_string(),
            display_identity: DisplayIdentity {
                display_name: name.to_string(),
                handle: handle.map(str::to_string),
                title: title.map(str::to_string),
            },
            harness_policy: HarnessModelPolicy {
                default_harness: "claude".to_string(),
                explicit_model: None,
            },
            instructions: String::new(),
            memories: Vec::new(),
            responsibilities: Vec::new(),
            current_session: None,
            created_at: 0.0,
            updated_at: 0.0,
        }
    }

    #[test]
    fn agents_md_carries_identity_instructions_and_memories() {
        let mut subject = bot("Arya Stark", Some("arya-stark"), Some("Scout"));
        subject.instructions = "Review incoming PRs.".to_string();
        subject.memories = vec!["Prefers terse replies.".to_string(), "  ".to_string()];
        let rendered = render_agents_md(&subject);
        assert!(rendered.starts_with("# Arya Stark\n"));
        assert!(rendered.contains("- Name: Arya Stark"));
        assert!(rendered.contains("- Handle: @arya-stark"));
        assert!(rendered.contains("- Role: Scout"));
        assert!(rendered.contains("## Standing instructions\n\nReview incoming PRs."));
        assert!(rendered.contains("## Memories\n\n- Prefers terse replies."));
        // Blank memory entries never become bullets.
        assert!(!rendered.contains("- \n"));
    }

    #[test]
    fn agents_md_is_honest_when_instructions_are_absent() {
        let subject = bot("Hodor", None, None);
        let rendered = render_agents_md(&subject);
        assert!(
            rendered.contains("## Standing instructions\n\nNo standing instructions recorded.")
        );
        assert!(!rendered.contains("## Memories"));
        assert!(!rendered.contains("- Handle:"));
        assert!(!rendered.contains("- Role:"));
    }

    #[test]
    fn agents_md_describes_only_real_discovery_commands() {
        let rendered = render_agents_md(&bot("Arya Stark", None, None));
        for command in [
            "drogon-cli status --json",
            "drogon-cli agent-context",
            "drogon-cli skills list",
            "drogon-cli skills get --topic drogon-cli",
            "drogon-cli skills get --topic orchestration",
        ] {
            assert!(
                rendered.contains(command),
                "expected the honest discovery command {command:?} in:\n{rendered}"
            );
        }
    }

    /// The Mentu capability is optional, so the Bot's identity file must say
    /// how to CHECK before promising a recipe, and name the two verbs that
    /// exist (`mentu status`, `mentu open`) — never an invented one.
    #[test]
    fn agents_md_gates_mentu_on_a_real_environment_check() {
        let rendered = render_agents_md(&bot("Arya Stark", None, None));
        for fragment in [
            "drogon-cli mentu status --workspace <ID> --json",
            "drogon-cli mentu open --workspace <ID> --recipe <ID>",
            "not_installed",
            "OPTIONAL",
        ] {
            assert!(
                rendered.contains(fragment),
                "expected {fragment:?} in:\n{rendered}"
            );
        }
    }

    #[test]
    fn claude_md_points_at_agents_md_instead_of_duplicating_it() {
        let mut subject = bot("Arya Stark", Some("arya-stark"), Some("Scout"));
        subject.instructions = "Review incoming PRs.".to_string();
        let claude = render_claude_md(&subject);
        assert!(claude.contains("AGENTS.md"));
        assert!(!claude.contains("Review incoming PRs."));
        assert!(!claude.contains("Standing instructions"));
    }

    #[test]
    fn writes_both_files_and_overwrites_a_stale_identity() {
        let directory = tempfile::tempdir().unwrap();
        let mut subject = bot("Arya Stark", Some("arya-stark"), None);
        subject.instructions = "First instructions.".to_string();
        assert!(write_bot_context_files(directory.path(), &subject).unwrap());

        let agents = std::fs::read_to_string(directory.path().join(AGENTS_FILE_NAME)).unwrap();
        assert!(agents.contains("Arya Stark"));
        assert!(agents.contains("First instructions."));
        assert!(directory.path().join(CLAUDE_FILE_NAME).exists());

        // An identity edit is reflected on the next write, and the stale
        // text is gone (never left behind beside the fresh identity).
        subject.display_identity.display_name = "Arya of House Stark".to_string();
        subject.instructions = "Second instructions.".to_string();
        subject.memories = vec!["New memory.".to_string()];
        assert!(write_bot_context_files(directory.path(), &subject).unwrap());
        let agents = std::fs::read_to_string(directory.path().join(AGENTS_FILE_NAME)).unwrap();
        assert!(agents.contains("Arya of House Stark"));
        assert!(agents.contains("Second instructions."));
        assert!(agents.contains("- New memory."));
        assert!(!agents.contains("First instructions."));

        // Rewriting identical content is a no-op (idempotent), so a
        // session open does not churn mtimes for nothing.
        assert!(!write_bot_context_files(directory.path(), &subject).unwrap());
        assert!(!directory.path().join("AGENTS.md.drogon-tmp").exists());
    }
}
