// Persisted-renderer contract extraction — Lovecast Inc. MIT source
// c97906287bb7a390b25e2025b600d9fb3c25d9c3,
// src/shared/feature-interaction-catalog.ts
// (SHA256 0015a3cfc624d9dd800d54dba6cc420e4e7505131cedc3314f38c1ed03eeda80),
// declarations: FeatureInteractionId. Type-only extraction; the definition
// table and id-value array stay in the pinned source.

export type FeatureInteractionId =
  | 'workspace-board'
  | 'workspace-agent-sessions'
  | 'workspace-board-actions'
  | 'cmd-j'
  | 'cmd-j-workspace-open'
  | 'cmd-j-browser-page-open'
  | 'cmd-j-settings-open'
  | 'cmd-j-quick-action'
  | 'cmd-j-create-workspace'
  | 'browser'
  | 'client-hosted-browser'
  | 'browser-tab-created'
  | 'tasks'
  | 'github-tasks'
  | 'gitlab-tasks'
  | 'linear-tasks'
  | 'jira-tasks'
  | 'automations'
  | 'automation-created'
  | 'automation-run'
  | 'browser-annotations'
  | 'browser-annotations-sent-to-agent'
  | 'browser-grab'
  | 'markdown-file-created'
  | 'workspace-creation'
  | 'agent-browser-setup'
  | 'agent-browser-use'
  | 'agent-orchestration-setup'
  | 'agent-orchestration'
  | 'ephemeral-vm-setup'
  | 'mobile-emulator-agent-setup'
  | 'ai-commit-generation'
  | 'ai-pr-generation'
  | 'claude-account-switching'
  | 'computer-use-setup'
  | 'computer-use'
  | 'codex-account-switching'
  | 'cookie-import'
  | 'floating-workspace'
  | 'floating-workspace-hidden'
  | 'mobile-pairing'
  | 'notifications'
  | 'ports'
  | 'quick-commands'
  | 'resource-manager'
  | 'review-notes'
  | 'ssh'
  | 'terminal-pane-split'
  | 'terminal-panes'
  | 'terminal-tabs'
  | 'tab-splits'
  | 'usage-tracking'
  | 'voice-dictation'
  | 'workspace-cleanup'
