// MIT Copyright (c) 2026 Lovecast Inc.
// Ported from the Orca reference (read-only):
//   src/shared/keybindings/definitions-core-1.ts
//   src/shared/keybindings/definitions-core-2.ts
//   src/shared/keybindings/definitions-core-3.ts
//   src/shared/keybindings/definitions-core-4.ts
//   src/shared/keybindings/definitions.ts
//   src/shared/keybindings/types.ts
// Adapted only at the data boundary: Drogon keeps a status field for the
// settings UI and uses string ids instead of the fork's generated union.
// Default ids, titles, groups, scopes, platform chords and terminal flags are
// otherwise source definitions verbatim. Empty source rows remain registered
// so rebinding and conflict checks cannot silently steal a future chord.

export type KeybindingScope =
  | "global"
  | "tabs"
  | "terminal"
  | "browser"
  | "editor"
  | "fileExplorer"
  | "composer"
  | "settings";

export type KeybindingPlatform = "darwin" | "linux" | "win32";

export interface PlatformBindings {
  readonly darwin: readonly string[];
  readonly linux: readonly string[];
  readonly win32: readonly string[];
}

/** One binding applies to every desktop platform. */
export function platformBindings(
  bindings: readonly string[],
): PlatformBindings {
  return { darwin: bindings, linux: bindings, win32: bindings };
}

export type KeybindingStatus =
  | { kind: "implemented" }
  | { kind: "menu"; note: string }
  | { kind: "disabled"; reason: string };

export interface KeybindingDefinition {
  readonly id: string;
  readonly title: string;
  readonly group: string;
  readonly scope: KeybindingScope;
  readonly searchKeywords: readonly string[];
  readonly defaultBindings: PlatformBindings;
  readonly allowInTerminal?: boolean;
  readonly allowBareKeybindings?: boolean;
  readonly allowShiftOnlyKeybindings?: boolean;
  readonly conflictGroup?: string;
  /** Digit-index rows store a representative chord; any of 1-9 fires it. */
  readonly digitIndex?: boolean;
  /** Drogon UI status used by the rebinding surface. */
  readonly status: KeybindingStatus;
}

const IMPLEMENTED: KeybindingStatus = { kind: "implemented" };

function same(bindings: readonly string[]): PlatformBindings {
  return platformBindings(bindings);
}

/**
 * Full source keybinding table in core-1 → core-4 order. The source app
 * appends generated agent rows after this table; the static rows below mirror
 * that behavior so Settings and conflict checks see the same catalog.
 */
export const KEYBINDING_DEFINITIONS: readonly KeybindingDefinition[] = [
  {
    id: "worktree.quickOpen",
    title: "Go to File",
    group: "Global",
    scope: "global",
    searchKeywords: ["shortcut", "global", "file", "quick open"],
    defaultBindings: platformBindings(["Mod+P"]),
    status: IMPLEMENTED,
  },
  {
    id: "app.settings",
    title: "Open Settings",
    group: "Global",
    scope: "global",
    searchKeywords: ["shortcut", "settings", "preferences"],
    defaultBindings: platformBindings(["Mod+Comma"]),
    conflictGroup: "menu",
    status: IMPLEMENTED,
  },
  {
    id: "app.forceReload",
    title: "Force Reload",
    group: "Global",
    scope: "global",
    searchKeywords: ["shortcut", "reload", "refresh", "force"],
    defaultBindings: platformBindings(["Mod+Shift+R"]),
    conflictGroup: "menu",
    status: IMPLEMENTED,
  },
  {
    id: "worktree.palette",
    title: "Switch worktree",
    group: "Global",
    scope: "global",
    searchKeywords: ["shortcut", "global", "worktree", "switch", "jump"],
    defaultBindings: {
      darwin: ["Mod+J"],
      linux: ["Mod+Shift+J"],
      win32: ["Mod+Shift+J"],
    },
    status: IMPLEMENTED,
  },
  {
    id: "worktree.navigateUp",
    title: "Previous worktree",
    group: "Global",
    scope: "global",
    searchKeywords: ["shortcut", "global", "worktree", "previous", "up"],
    defaultBindings: platformBindings(["Mod+Shift+ArrowUp"]),
    status: IMPLEMENTED,
  },
  {
    id: "worktree.navigateDown",
    title: "Next worktree",
    group: "Global",
    scope: "global",
    searchKeywords: ["shortcut", "global", "worktree", "next", "down"],
    defaultBindings: platformBindings(["Mod+Shift+ArrowDown"]),
    status: IMPLEMENTED,
  },
  {
    id: "workspace.create",
    title: "Create worktree",
    group: "Global",
    scope: "global",
    searchKeywords: [
      "shortcut",
      "global",
      "worktree",
      "create",
      "new workspace",
    ],
    defaultBindings: platformBindings(["Mod+N", "Mod+Shift+N"]),
    status: IMPLEMENTED,
  },
  {
    id: "workspace.rename",
    title: "Rename worktree",
    group: "Global",
    scope: "global",
    conflictGroup: "workspace-shell",
    searchKeywords: [
      "shortcut",
      "global",
      "worktree",
      "rename",
      "workspace",
      "title",
    ],
    // Why: macOS only — Windows/Linux Ctrl+Alt+R has no safe default (Ctrl+R reverse-search, Ctrl+Shift+R reload are taken).
    defaultBindings: {
      darwin: ["Mod+Alt+R"],
      linux: [],
      win32: [],
    },
    status: IMPLEMENTED,
  },
  {
    id: "workspace.delete",
    title: "Delete Workspace",
    group: "Global",
    scope: "global",
    searchKeywords: [
      "shortcut",
      "global",
      "workspace",
      "current workspace",
      "worktree",
      "delete",
      "remove",
      "trash",
    ],
    // Why: Backspace avoids the terminal pane's D-based split shortcuts on every platform.
    defaultBindings: platformBindings(["Mod+Shift+Backspace"]),
    allowInTerminal: true,
    status: IMPLEMENTED,
  },
  {
    id: "workspace.openBoard",
    title: "Toggle Workspace Board",
    group: "Global",
    scope: "global",
    searchKeywords: [
      "shortcut",
      "global",
      "workspace",
      "board",
      "kanban",
      "worktree",
      "toggle",
      "open",
      "close",
    ],
    // Why: configurable but unbound by default, to not take a global chord from terminal/browser/editor users.
    defaultBindings: platformBindings([]),
    allowInTerminal: true,
    status: IMPLEMENTED,
  },
  {
    id: "dashboard.toggle",
    title: "Toggle Agent Dashboard",
    group: "Global",
    scope: "global",
    searchKeywords: [
      "shortcut",
      "global",
      "agent",
      "agents",
      "dashboard",
      "kanban",
      "board",
      "toggle",
      "open",
      "close",
    ],
    // Why: configurable but unbound by default, matching workspace.openBoard — an
    // experimental surface must not claim a global chord from terminal users.
    defaultBindings: platformBindings([]),
    allowInTerminal: true,
    status: IMPLEMENTED,
  },
  {
    id: "workspace.selectByIndex",
    title: "Select Workspace 1–9",
    group: "Global",
    scope: "global",
    searchKeywords: [
      "shortcut",
      "global",
      "workspace",
      "worktree",
      "select",
      "switch",
      "number",
      "digit",
      "1-9",
      "index",
    ],
    // Why: one remappable row covers the whole 1-9 range (stored chord is a representative; any of 1-9 fires it).
    defaultBindings: platformBindings(["Mod+1"]),
    digitIndex: true,
    status: IMPLEMENTED,
  },
  {
    id: "voice.dictation",
    title: "Dictation",
    group: "Global",
    scope: "global",
    searchKeywords: ["shortcut", "dictation", "voice", "speech", "microphone"],
    defaultBindings: platformBindings(["Mod+E"]),
    status: IMPLEMENTED,
  },
  {
    id: "view.tasks",
    title: "Open Tasks",
    group: "Global",
    scope: "global",
    searchKeywords: ["shortcut", "tasks", "github issues", "linear"],
    defaultBindings: platformBindings([]),
    status: IMPLEMENTED,
  },
  {
    id: "sidebar.left.toggle",
    title: "Toggle Sidebar",
    group: "Global",
    scope: "global",
    searchKeywords: ["shortcut", "sidebar", "left"],
    defaultBindings: platformBindings(["Mod+B"]),
    status: IMPLEMENTED,
  },
  {
    id: "sidebar.right.toggle",
    title: "Toggle Right Sidebar",
    group: "Global",
    scope: "global",
    searchKeywords: ["shortcut", "sidebar", "right"],
    defaultBindings: platformBindings(["Mod+L"]),
    status: IMPLEMENTED,
  },
  {
    id: "sidebar.explorer.toggle",
    title: "Show Explorer",
    group: "Global",
    scope: "global",
    searchKeywords: ["shortcut", "sidebar", "explorer", "files"],
    defaultBindings: platformBindings(["Mod+Shift+E"]),
    status: IMPLEMENTED,
  },
  {
    id: "sidebar.search.toggle",
    title: "Show Search",
    group: "Global",
    scope: "global",
    searchKeywords: ["shortcut", "sidebar", "search"],
    defaultBindings: platformBindings(["Mod+Shift+F"]),
    status: IMPLEMENTED,
  },
  {
    id: "sidebar.sourceControl.toggle",
    title: "Show Source Control",
    group: "Global",
    scope: "global",
    searchKeywords: ["shortcut", "sidebar", "source control", "git"],
    defaultBindings: platformBindings(["Mod+Shift+G"]),
    status: IMPLEMENTED,
  },
  {
    id: "sidebar.checks.toggle",
    title: "Show Checks",
    group: "Global",
    scope: "global",
    searchKeywords: ["shortcut", "sidebar", "checks", "ci"],
    defaultBindings: platformBindings([]),
    status: IMPLEMENTED,
  },
  {
    id: "sidebar.ports.toggle",
    title: "Show Ports",
    group: "Global",
    scope: "global",
    searchKeywords: ["shortcut", "sidebar", "ports"],
    defaultBindings: {
      darwin: ["Mod+Shift+I"],
      linux: [],
      win32: [],
    },
    status: IMPLEMENTED,
  },
  {
    id: "sidebar.sleepingWorkspaces.toggle",
    title: "Toggle Sleeping Workspaces",
    group: "Global",
    scope: "global",
    searchKeywords: [
      "shortcut",
      "sidebar",
      "sleeping",
      "asleep",
      "workspaces",
      "worktree",
      "filter",
      "show",
      "hide",
    ],
    // Why: ship unbound (issue #5209 asks users to assign it), avoiding a claimed cross-platform chord.
    defaultBindings: platformBindings([]),
    status: IMPLEMENTED,
  },
  {
    id: "sidebar.focusWorktreeList",
    title: "Focus worktree list",
    group: "Global",
    scope: "global",
    searchKeywords: ["shortcut", "sidebar", "worktree", "focus"],
    // Why: keep zoom.reset on the browser-standard Mod+0; this chord was unreachable while it shared that default (#8584).
    defaultBindings: platformBindings(["Mod+Shift+0"]),
    status: IMPLEMENTED,
  },
  {
    id: "floatingTerminal.toggle",
    title: "Toggle Floating Terminal",
    group: "Global",
    scope: "global",
    searchKeywords: ["shortcut", "floating terminal", "terminal"],
    defaultBindings: platformBindings(["Mod+Alt+A"]),
    allowInTerminal: true,
    status: IMPLEMENTED,
  },
  {
    id: "floatingWorkspace.maximize",
    title: "Maximize Floating Workspace Panel",
    group: "Global",
    scope: "global",
    searchKeywords: [
      "shortcut",
      "floating",
      "workspace",
      "panel",
      "floating workspace",
      "workspace panel",
      "maximize",
      "expand",
    ],
    // Why: pairs with floatingTerminal.toggle (Cmd+Opt+A) so maximize stays one-handed; macOS-only, Linux/Windows unbound.
    defaultBindings: {
      darwin: ["Mod+Alt+Shift+A"],
      linux: [],
      win32: [],
    },
    allowInTerminal: true,
    status: IMPLEMENTED,
  },
  {
    id: "floatingWorkspace.minimize",
    title: "Minimize Floating Workspace Panel",
    group: "Global",
    scope: "global",
    searchKeywords: [
      "shortcut",
      "floating",
      "workspace",
      "panel",
      "floating workspace",
      "workspace panel",
      "minimize",
      "hide",
    ],
    // Why: unbound everywhere since floatingTerminal.toggle owns show/hide; this exists only for an explicit user-bound "hide panel" shortcut.
    defaultBindings: {
      darwin: [],
      linux: [],
      win32: [],
    },
    allowInTerminal: true,
    status: IMPLEMENTED,
  },
  {
    id: "zoom.in",
    title: "Zoom In",
    group: "Global",
    scope: "global",
    searchKeywords: ["shortcut", "zoom", "in", "scale"],
    defaultBindings: platformBindings([
      "Mod+Equal",
      "Mod+Shift+Plus",
      "Mod+NumpadAdd",
    ]),
    status: IMPLEMENTED,
  },
  {
    id: "zoom.out",
    title: "Zoom Out",
    group: "Global",
    scope: "global",
    searchKeywords: ["shortcut", "zoom", "out", "scale"],
    defaultBindings: platformBindings(["Mod+Minus", "Mod+NumpadSubtract"]),
    status: IMPLEMENTED,
  },
  {
    id: "zoom.reset",
    title: "Reset Size",
    group: "Global",
    scope: "global",
    searchKeywords: ["shortcut", "zoom", "reset", "size", "actual"],
    defaultBindings: platformBindings(["Mod+0"]),
    status: IMPLEMENTED,
  },
  {
    id: "worktree.history.back",
    title: "Worktree History Back",
    group: "Global",
    scope: "global",
    searchKeywords: ["shortcut", "worktree", "history", "back"],
    defaultBindings: platformBindings(["Mod+Alt+ArrowLeft"]),
    allowInTerminal: true,
    status: IMPLEMENTED,
  },
  {
    id: "worktree.history.forward",
    title: "Worktree History Forward",
    group: "Global",
    scope: "global",
    searchKeywords: ["shortcut", "worktree", "history", "forward"],
    defaultBindings: platformBindings(["Mod+Alt+ArrowRight"]),
    allowInTerminal: true,
    status: IMPLEMENTED,
  },
  {
    id: "tab.newTerminal",
    title: "New terminal tab",
    group: "Tabs",
    scope: "tabs",
    searchKeywords: ["shortcut", "tab", "terminal", "new"],
    defaultBindings: platformBindings(["Mod+T"]),
    status: IMPLEMENTED,
  },
  {
    id: "tab.newAgent",
    title: "New agent tab (default agent)",
    group: "Tabs",
    scope: "tabs",
    searchKeywords: ["shortcut", "tab", "agent", "new", "default", "launch"],
    // Why: macOS only — Windows Ctrl+Alt is AltGr and Linux Ctrl+Alt+T is the desktop "open terminal", so no safe default there.
    defaultBindings: {
      darwin: ["Mod+Alt+T"],
      linux: [],
      win32: [],
    },
    status: IMPLEMENTED,
  },
  {
    id: "tab.newBrowser",
    title: "New browser tab",
    group: "Tabs",
    scope: "tabs",
    searchKeywords: ["shortcut", "tab", "browser", "new"],
    defaultBindings: platformBindings(["Mod+Shift+B"]),
    status: IMPLEMENTED,
  },
  {
    id: "tab.newSimulator",
    title: "New mobile emulator tab",
    group: "Tabs",
    scope: "tabs",
    searchKeywords: [
      "shortcut",
      "tab",
      "simulator",
      "emulator",
      "mobile",
      "ios",
      "new",
    ],
    // Why: keep explorer on Mod+Shift+E (VS Code muscle memory); emulator is macOS-only and less common, so it yields to a free chord (#8533).
    defaultBindings: {
      darwin: ["Mod+Alt+Shift+E"],
      linux: [],
      win32: [],
    },
    status: IMPLEMENTED,
  },
  {
    id: "tab.newMarkdown",
    title: "New markdown tab",
    group: "Tabs",
    scope: "tabs",
    searchKeywords: ["shortcut", "tab", "markdown", "file", "new"],
    defaultBindings: platformBindings(["Mod+Shift+M"]),
    status: IMPLEMENTED,
  },
  {
    id: "tab.openMarkdown",
    title: "Open markdown tab",
    group: "Tabs",
    scope: "tabs",
    searchKeywords: ["shortcut", "tab", "markdown", "file", "open"],
    defaultBindings: platformBindings(["Mod+Shift+O"]),
    status: IMPLEMENTED,
  },
  {
    id: "tab.close",
    title: "Close active tab",
    group: "Tabs",
    scope: "tabs",
    searchKeywords: ["shortcut", "close", "tab", "pane"],
    defaultBindings: platformBindings(["Mod+W"]),
    status: IMPLEMENTED,
  },
  {
    id: "tab.closeAll",
    title: "Close all editor tabs",
    group: "Tabs",
    scope: "tabs",
    searchKeywords: ["shortcut", "close", "all", "tabs", "files", "editors"],
    defaultBindings: platformBindings(["Mod+Alt+W"]),
    status: IMPLEMENTED,
  },
  {
    id: "tab.rename",
    title: "Rename active tab",
    group: "Tabs",
    scope: "tabs",
    conflictGroup: "workspace-shell",
    searchKeywords: ["shortcut", "tab", "rename", "title", "label"],
    // Why: macOS only — Cmd+R is free in app/terminal focus; on Windows/Linux Ctrl+R is shell reverse-search, so left unbound.
    defaultBindings: {
      darwin: ["Mod+R"],
      linux: [],
      win32: [],
    },
    status: IMPLEMENTED,
  },
  {
    id: "tab.reopenClosed",
    title: "Reopen closed tab",
    group: "Tabs",
    scope: "tabs",
    searchKeywords: ["shortcut", "tab", "reopen", "restore", "closed"],
    defaultBindings: platformBindings(["Mod+Shift+T"]),
    status: IMPLEMENTED,
  },
  {
    id: "tab.nextSameType",
    title: "Next tab (same type)",
    group: "Tab Navigation",
    scope: "tabs",
    searchKeywords: ["shortcut", "tab", "next", "switch", "cycle"],
    // Why: the widespread "switch tab" chord (Mod+Shift+Bracket) now drives all-types cycling; same-type moved to Mod+Alt for new installs.
    defaultBindings: platformBindings(["Mod+Alt+BracketRight"]),
    status: IMPLEMENTED,
  },
  {
    id: "tab.previousSameType",
    title: "Previous tab (same type)",
    group: "Tab Navigation",
    scope: "tabs",
    searchKeywords: ["shortcut", "tab", "previous", "switch", "cycle"],
    defaultBindings: platformBindings(["Mod+Alt+BracketLeft"]),
    status: IMPLEMENTED,
  },
  {
    id: "tab.nextAllTypes",
    title: "Next tab (all types)",
    group: "Tab Navigation",
    scope: "tabs",
    searchKeywords: [
      "shortcut",
      "tab",
      "next",
      "switch",
      "cycle",
      "all",
      "any",
    ],
    defaultBindings: platformBindings(["Mod+Shift+BracketRight"]),
    status: IMPLEMENTED,
  },
  {
    id: "tab.previousAllTypes",
    title: "Previous tab (all types)",
    group: "Tab Navigation",
    scope: "tabs",
    searchKeywords: [
      "shortcut",
      "tab",
      "previous",
      "switch",
      "cycle",
      "all",
      "any",
    ],
    defaultBindings: platformBindings(["Mod+Shift+BracketLeft"]),
    status: IMPLEMENTED,
  },
  {
    id: "tab.previousRecent",
    title: "Previous recent tab",
    group: "Tab Navigation",
    scope: "tabs",
    searchKeywords: ["shortcut", "tab", "recent", "mru", "switch", "last used"],
    defaultBindings: platformBindings(["Ctrl+Tab"]),
    allowInTerminal: true,
    status: IMPLEMENTED,
  },
  {
    id: "tab.nextTerminal",
    title: "Next terminal tab",
    group: "Tab Navigation",
    scope: "tabs",
    searchKeywords: ["shortcut", "tab", "terminal", "next", "switch"],
    defaultBindings: platformBindings(["Ctrl+PageDown"]),
    allowInTerminal: true,
    status: IMPLEMENTED,
  },
  {
    id: "tab.previousTerminal",
    title: "Previous terminal tab",
    group: "Tab Navigation",
    scope: "tabs",
    searchKeywords: ["shortcut", "tab", "terminal", "previous", "switch"],
    defaultBindings: platformBindings(["Ctrl+PageUp"]),
    allowInTerminal: true,
    status: IMPLEMENTED,
  },
  {
    id: "tab.selectByIndex",
    title: "Select Tab 1–9",
    group: "Tab Navigation",
    scope: "tabs",
    // Why: no shared conflictGroup with workspace.selectByIndex so swapping their modifiers isn't a false conflict; safe because resolveWindowShortcutAction checks the workspace range first.
    searchKeywords: [
      "shortcut",
      "tab",
      "select",
      "switch",
      "number",
      "digit",
      "1-9",
      "index",
    ],
    // Why: representative chord for the 1-9 range (see workspace.selectByIndex); each platform avoids the workspace-jump chord (Mod+1-9).
    defaultBindings: {
      darwin: ["Ctrl+1"],
      linux: ["Alt+1"],
      win32: ["Alt+1"],
    },
    digitIndex: true,
    status: IMPLEMENTED,
  },
  {
    id: "tab.openQuickCommandsMenu",
    title: "Toggle Quick Commands menu",
    group: "Quick Commands",
    scope: "tabs",
    // Why: this tab-scoped action is also routed through the main-window allowlist, so Settings must warn when it shadows global chords.
    conflictGroup: "global",
    searchKeywords: [
      "shortcut",
      "quick",
      "command",
      "menu",
      "tab",
      "group",
      "toggle",
    ],
    defaultBindings: platformBindings([]),
    status: IMPLEMENTED,
  },
  {
    id: "browser.find",
    title: "Find in Browser",
    group: "Browser",
    scope: "browser",
    searchKeywords: ["shortcut", "browser", "find", "search"],
    defaultBindings: platformBindings(["Mod+F"]),
    status: IMPLEMENTED,
  },
  {
    id: "browser.back",
    title: "Go Back in Browser",
    group: "Browser",
    scope: "browser",
    searchKeywords: ["shortcut", "browser", "history", "back", "previous"],
    defaultBindings: {
      darwin: ["Mod+BracketLeft"],
      linux: ["Alt+ArrowLeft"],
      win32: ["Alt+ArrowLeft"],
    },
    status: IMPLEMENTED,
  },
  {
    id: "browser.forward",
    title: "Go Forward in Browser",
    group: "Browser",
    scope: "browser",
    searchKeywords: ["shortcut", "browser", "history", "forward", "next"],
    defaultBindings: {
      darwin: ["Mod+BracketRight"],
      linux: ["Alt+ArrowRight"],
      win32: ["Alt+ArrowRight"],
    },
    status: IMPLEMENTED,
  },
  {
    id: "browser.reload",
    title: "Reload Browser Page",
    group: "Browser",
    scope: "browser",
    searchKeywords: ["shortcut", "browser", "reload", "refresh"],
    defaultBindings: platformBindings(["Mod+R"]),
    status: IMPLEMENTED,
  },
  {
    id: "browser.hardReload",
    title: "Hard Reload Browser Page",
    group: "Browser",
    scope: "browser",
    searchKeywords: ["shortcut", "browser", "reload", "refresh", "cache"],
    defaultBindings: platformBindings(["Mod+Shift+R"]),
    status: IMPLEMENTED,
  },
  {
    id: "browser.focusAddressBar",
    title: "Focus Browser Address Bar",
    group: "Browser",
    scope: "browser",
    searchKeywords: ["shortcut", "browser", "address", "url", "location"],
    defaultBindings: platformBindings(["Mod+L"]),
    status: IMPLEMENTED,
  },
  {
    id: "browser.grabElement",
    title: "Grab Page Element",
    group: "Browser",
    scope: "browser",
    searchKeywords: ["shortcut", "browser", "grab", "copy", "element"],
    defaultBindings: platformBindings(["Mod+C"]),
    status: IMPLEMENTED,
  },
  {
    id: "editor.find",
    title: "Find in editor",
    group: "Editors",
    scope: "editor",
    searchKeywords: ["shortcut", "editor", "find", "search"],
    defaultBindings: platformBindings(["Mod+F"]),
    status: IMPLEMENTED,
  },
  {
    id: "editor.replace",
    title: "Replace in editor",
    group: "Editors",
    scope: "editor",
    searchKeywords: ["shortcut", "editor", "replace", "find", "search"],
    // Why: match the source editor's native replace shortcut per platform.
    defaultBindings: {
      darwin: ["Mod+Alt+F"],
      linux: ["Mod+H"],
      win32: ["Mod+H"],
    },
    status: IMPLEMENTED,
  },
  {
    id: "editor.save",
    title: "Save File",
    group: "Editors",
    scope: "editor",
    searchKeywords: ["shortcut", "editor", "save"],
    defaultBindings: platformBindings(["Mod+S"]),
    status: IMPLEMENTED,
  },
  {
    id: "editor.markdownPreview",
    title: "Show Markdown Preview",
    group: "Editors",
    scope: "editor",
    searchKeywords: ["shortcut", "editor", "markdown", "preview"],
    defaultBindings: platformBindings(["Mod+Shift+V"]),
    status: IMPLEMENTED,
  },
  {
    id: "editor.toggleWordWrap",
    title: "Toggle Word Wrap",
    group: "Editors",
    scope: "editor",
    searchKeywords: [
      "shortcut",
      "editor",
      "word wrap",
      "wrap",
      "long lines",
      "soft wrap",
    ],
    // Why: Alt+Z matches VS Code; bare Alt+letter is not AltGr, so it stays cross-platform (#9974).
    defaultBindings: platformBindings(["Alt+Z"]),
    status: IMPLEMENTED,
  },
  {
    id: "editor.copyContext",
    title: "Copy Context",
    group: "Editors",
    scope: "editor",
    searchKeywords: ["shortcut", "editor", "copy", "context"],
    defaultBindings: platformBindings(["Mod+Alt+C"]),
    status: IMPLEMENTED,
  },
  // Why: F7 / Shift+F7 mirror VS Code / JetBrains diff-change nav; function keys are safe bare/Shift, so both opt into allowBareKeybindings.
  {
    id: "editor.previousChange",
    title: "Go to Previous Change",
    group: "Editors",
    scope: "editor",
    searchKeywords: [
      "shortcut",
      "editor",
      "diff",
      "change",
      "hunk",
      "previous",
    ],
    defaultBindings: platformBindings(["Shift+F7"]),
    allowBareKeybindings: true,
    status: IMPLEMENTED,
  },
  {
    id: "editor.nextChange",
    title: "Go to Next Change",
    group: "Editors",
    scope: "editor",
    searchKeywords: ["shortcut", "editor", "diff", "change", "hunk", "next"],
    defaultBindings: platformBindings(["F7"]),
    allowBareKeybindings: true,
    status: IMPLEMENTED,
  },
  {
    id: "editor.addReviewNote",
    title: "Add Review Note",
    group: "Editors",
    scope: "editor",
    searchKeywords: [
      "shortcut",
      "editor",
      "markdown",
      "note",
      "comment",
      "annotation",
      "review",
    ],
    // Why: Ctrl+Alt+letter is AltGr text input on Windows/Linux, so an editor default must not reserve chars like Polish `ń`.
    defaultBindings: platformBindings(["Mod+Shift+A"]),
    status: IMPLEMENTED,
  },
  {
    id: "sourceControl.sendReviewNotes",
    title: "Send Review Notes to Agent",
    group: "Global",
    scope: "global",
    // Why: fires from the global capture handler even while the editor is focused, so Settings must warn on collisions with editor chords (e.g. Add Review Note) too, not just global ones.
    conflictGroup: "editor",
    searchKeywords: [
      "shortcut",
      "source control",
      "diff",
      "notes",
      "send",
      "agent",
      "review",
      "annotate",
    ],
    // Why: unbound by default so it never collides with existing chords; users opt in via Settings.
    defaultBindings: platformBindings([]),
    status: IMPLEMENTED,
  },
  {
    id: "fileExplorer.undo",
    title: "Undo file operation",
    group: "File Explorer",
    scope: "fileExplorer",
    searchKeywords: ["shortcut", "file explorer", "undo"],
    defaultBindings: platformBindings(["Mod+Z"]),
    status: IMPLEMENTED,
  },
  {
    id: "fileExplorer.redo",
    title: "Redo file operation",
    group: "File Explorer",
    scope: "fileExplorer",
    searchKeywords: ["shortcut", "file explorer", "redo"],
    defaultBindings: {
      darwin: ["Mod+Shift+Z"],
      linux: ["Mod+Shift+Z", "Ctrl+Y"],
      win32: ["Mod+Shift+Z", "Ctrl+Y"],
    },
    status: IMPLEMENTED,
  },
  {
    id: "fileExplorer.copyPath",
    title: "Copy file path",
    group: "File Explorer",
    scope: "fileExplorer",
    searchKeywords: ["shortcut", "file explorer", "copy", "path"],
    defaultBindings: {
      darwin: ["Mod+Alt+C"],
      linux: ["Alt+Shift+C"],
      win32: ["Alt+Shift+C"],
    },
    status: IMPLEMENTED,
  },
  {
    id: "fileExplorer.copyRelativePath",
    title: "Copy relative file path",
    group: "File Explorer",
    scope: "fileExplorer",
    searchKeywords: ["shortcut", "file explorer", "copy", "relative", "path"],
    defaultBindings: platformBindings(["Mod+Alt+Shift+C"]),
    status: IMPLEMENTED,
  },
  {
    id: "fileExplorer.delete",
    title: "Delete file",
    group: "File Explorer",
    scope: "fileExplorer",
    searchKeywords: ["shortcut", "file explorer", "delete", "remove", "trash"],
    defaultBindings: {
      darwin: ["Mod+Backspace", "Delete"],
      linux: ["Delete"],
      win32: ["Delete"],
    },
    allowBareKeybindings: true,
    status: IMPLEMENTED,
  },
  {
    id: "settings.search",
    title: "Search Settings",
    group: "Settings",
    scope: "settings",
    searchKeywords: ["shortcut", "settings", "search", "find"],
    defaultBindings: platformBindings(["Mod+F"]),
    status: IMPLEMENTED,
  },
  {
    id: "terminal.copySelection",
    title: "Copy terminal selection",
    group: "Terminal Panes",
    scope: "terminal",
    searchKeywords: ["shortcut", "terminal", "copy", "selection"],
    defaultBindings: {
      darwin: ["Mod+C"],
      linux: ["Ctrl+Shift+C", "Ctrl+C"],
      win32: ["Ctrl+Shift+C", "Ctrl+C"],
    },
    status: IMPLEMENTED,
  },
  {
    id: "terminal.selectAll",
    title: "Select all terminal text",
    group: "Terminal Panes",
    scope: "terminal",
    searchKeywords: ["shortcut", "terminal", "select", "all"],
    defaultBindings: {
      darwin: ["Mod+A"],
      linux: ["Ctrl+Shift+A"],
      win32: ["Ctrl+Shift+A"],
    },
    status: IMPLEMENTED,
  },
  {
    id: "terminal.paste",
    title: "Paste into terminal",
    group: "Terminal Panes",
    scope: "terminal",
    searchKeywords: ["shortcut", "terminal", "paste", "clipboard"],
    defaultBindings: {
      darwin: ["Mod+V"],
      linux: ["Ctrl+V", "Ctrl+Shift+V", "Shift+Insert"],
      win32: ["Ctrl+V", "Ctrl+Shift+V", "Shift+Insert"],
    },
    status: IMPLEMENTED,
  },
  {
    id: "terminal.search",
    title: "Search active pane",
    group: "Terminal Panes",
    scope: "terminal",
    searchKeywords: ["shortcut", "terminal", "search", "find"],
    defaultBindings: platformBindings(["Mod+F"]),
    status: IMPLEMENTED,
  },
  {
    id: "terminal.clear",
    title: "Clear active pane",
    group: "Terminal Panes",
    scope: "terminal",
    searchKeywords: ["shortcut", "pane", "clear"],
    defaultBindings: platformBindings(["Mod+K"]),
    status: IMPLEMENTED,
  },
  {
    id: "terminal.focusNextPane",
    title: "Focus next pane",
    group: "Terminal Panes",
    scope: "terminal",
    searchKeywords: ["shortcut", "pane", "focus", "next"],
    defaultBindings: platformBindings(["Mod+BracketRight"]),
    status: IMPLEMENTED,
  },
  {
    id: "terminal.focusPreviousPane",
    title: "Focus previous pane",
    group: "Terminal Panes",
    scope: "terminal",
    searchKeywords: ["shortcut", "pane", "focus", "previous"],
    defaultBindings: platformBindings(["Mod+BracketLeft"]),
    status: IMPLEMENTED,
  },
  {
    id: "terminal.equalizePaneSizes",
    title: "Equalize pane sizes",
    group: "Terminal Panes",
    scope: "terminal",
    searchKeywords: [
      "shortcut",
      "pane",
      "split",
      "equalize",
      "resize",
      "balance",
      "size",
    ],
    defaultBindings: platformBindings([]),
    status: IMPLEMENTED,
  },
  {
    id: "terminal.expandPane",
    title: "Expand / collapse pane",
    group: "Terminal Panes",
    scope: "terminal",
    searchKeywords: ["shortcut", "pane", "expand", "collapse"],
    defaultBindings: platformBindings(["Mod+Shift+Enter"]),
    status: IMPLEMENTED,
  },
  {
    id: "terminal.setTitle",
    title: "Set Title…",
    group: "Terminal Panes",
    scope: "terminal",
    searchKeywords: [
      "shortcut",
      "terminal",
      "pane",
      "set title",
      "title",
      "rename",
    ],
    defaultBindings: platformBindings([]),
    status: IMPLEMENTED,
  },
  {
    id: "terminal.clearPaneTitle",
    title: "Clear Pane Title",
    group: "Terminal Panes",
    scope: "terminal",
    searchKeywords: [
      "shortcut",
      "terminal",
      "pane",
      "clear title",
      "remove title",
      "title",
    ],
    defaultBindings: platformBindings([]),
    status: IMPLEMENTED,
  },
  {
    id: "terminal.closePane",
    title: "Close active pane",
    group: "Terminal Panes",
    scope: "terminal",
    searchKeywords: ["shortcut", "pane", "close"],
    defaultBindings: platformBindings(["Mod+W"]),
    status: IMPLEMENTED,
  },
  {
    id: "terminal.splitRight",
    title: "Split terminal right",
    group: "Terminal Panes",
    scope: "terminal",
    searchKeywords: ["shortcut", "pane", "split", "right"],
    defaultBindings: {
      darwin: ["Mod+D"],
      linux: ["Mod+Shift+D"],
      win32: ["Mod+Shift+D"],
    },
    status: IMPLEMENTED,
  },
  {
    id: "terminal.splitDown",
    title: "Split terminal down",
    group: "Terminal Panes",
    scope: "terminal",
    searchKeywords: ["shortcut", "pane", "split", "down"],
    defaultBindings: {
      darwin: ["Mod+Shift+D"],
      linux: ["Alt+Shift+D"],
      win32: ["Alt+Shift+D"],
    },
    status: IMPLEMENTED,
  },
  {
    id: "terminal.switchInputSource",
    title: "Switch input source / language (native)",
    group: "Terminal Panes",
    scope: "terminal",
    searchKeywords: [
      "shortcut",
      "input",
      "source",
      "language",
      "korean",
      "english",
      "ime",
      "switch",
      "hangul",
      "layout",
    ],
    defaultBindings: {
      darwin: [],
      linux: [],
      win32: [],
    },
    // Why: macOS uses Shift+Space as an input-source shortcut; Orca otherwise rejects Shift-only bindings to avoid stealing typed text.
    allowShiftOnlyKeybindings: true,
    status: IMPLEMENTED,
  },
  {
    id: "tab.newAgent.claude",
    title: "New Claude tab",
    group: "Agents",
    scope: "tabs",
    searchKeywords: [
      "shortcut",
      "tab",
      "agent",
      "new",
      "launch",
      "claude",
      "claude",
    ],
    defaultBindings: same([]),
    status: IMPLEMENTED,
  },
  {
    id: "tab.newAgent.claude-agent-teams",
    title: "New Claude Agent Teams tab",
    group: "Agents",
    scope: "tabs",
    searchKeywords: [
      "shortcut",
      "tab",
      "agent",
      "new",
      "launch",
      "claude-agent-teams",
      "claude agent teams",
    ],
    defaultBindings: same([]),
    status: IMPLEMENTED,
  },
  {
    id: "tab.newAgent.openclaude",
    title: "New OpenClaude tab",
    group: "Agents",
    scope: "tabs",
    searchKeywords: [
      "shortcut",
      "tab",
      "agent",
      "new",
      "launch",
      "openclaude",
      "openclaude",
    ],
    defaultBindings: same([]),
    status: IMPLEMENTED,
  },
  {
    id: "tab.newAgent.codex",
    title: "New Codex tab",
    group: "Agents",
    scope: "tabs",
    searchKeywords: [
      "shortcut",
      "tab",
      "agent",
      "new",
      "launch",
      "codex",
      "codex",
    ],
    defaultBindings: same([]),
    status: IMPLEMENTED,
  },
  {
    id: "tab.newAgent.devin",
    title: "New Devin tab",
    group: "Agents",
    scope: "tabs",
    searchKeywords: [
      "shortcut",
      "tab",
      "agent",
      "new",
      "launch",
      "devin",
      "devin",
    ],
    defaultBindings: same([]),
    status: IMPLEMENTED,
  },
  {
    id: "tab.newAgent.ante",
    title: "New Ante tab",
    group: "Agents",
    scope: "tabs",
    searchKeywords: [
      "shortcut",
      "tab",
      "agent",
      "new",
      "launch",
      "ante",
      "ante",
    ],
    defaultBindings: same([]),
    status: IMPLEMENTED,
  },
  {
    id: "tab.newAgent.trae",
    title: "New Trae tab",
    group: "Agents",
    scope: "tabs",
    searchKeywords: [
      "shortcut",
      "tab",
      "agent",
      "new",
      "launch",
      "trae",
      "trae",
    ],
    defaultBindings: same([]),
    status: IMPLEMENTED,
  },
  {
    id: "tab.newAgent.autohand",
    title: "New Autohand Code tab",
    group: "Agents",
    scope: "tabs",
    searchKeywords: [
      "shortcut",
      "tab",
      "agent",
      "new",
      "launch",
      "autohand",
      "autohand code",
    ],
    defaultBindings: same([]),
    status: IMPLEMENTED,
  },
  {
    id: "tab.newAgent.opencode",
    title: "New OpenCode tab",
    group: "Agents",
    scope: "tabs",
    searchKeywords: [
      "shortcut",
      "tab",
      "agent",
      "new",
      "launch",
      "opencode",
      "opencode",
    ],
    defaultBindings: same([]),
    status: IMPLEMENTED,
  },
  {
    id: "tab.newAgent.mimo-code",
    title: "New MiMo Code tab",
    group: "Agents",
    scope: "tabs",
    searchKeywords: [
      "shortcut",
      "tab",
      "agent",
      "new",
      "launch",
      "mimo-code",
      "mimo code",
    ],
    defaultBindings: same([]),
    status: IMPLEMENTED,
  },
  {
    id: "tab.newAgent.pi",
    title: "New Pi tab",
    group: "Agents",
    scope: "tabs",
    searchKeywords: ["shortcut", "tab", "agent", "new", "launch", "pi", "pi"],
    defaultBindings: same([]),
    status: IMPLEMENTED,
  },
  {
    id: "tab.newAgent.omp",
    title: "New OMP tab",
    group: "Agents",
    scope: "tabs",
    searchKeywords: ["shortcut", "tab", "agent", "new", "launch", "omp", "omp"],
    defaultBindings: same([]),
    status: IMPLEMENTED,
  },
  {
    id: "tab.newAgent.prime-agent",
    title: "New Prime Agent tab",
    group: "Agents",
    scope: "tabs",
    searchKeywords: [
      "shortcut",
      "tab",
      "agent",
      "new",
      "launch",
      "prime-agent",
      "prime agent",
    ],
    defaultBindings: same([]),
    status: IMPLEMENTED,
  },
  {
    id: "tab.newAgent.gemini",
    title: "New Gemini tab",
    group: "Agents",
    scope: "tabs",
    searchKeywords: [
      "shortcut",
      "tab",
      "agent",
      "new",
      "launch",
      "gemini",
      "gemini",
    ],
    defaultBindings: same([]),
    status: IMPLEMENTED,
  },
  {
    id: "tab.newAgent.antigravity",
    title: "New Antigravity tab",
    group: "Agents",
    scope: "tabs",
    searchKeywords: [
      "shortcut",
      "tab",
      "agent",
      "new",
      "launch",
      "antigravity",
      "antigravity",
    ],
    defaultBindings: same([]),
    status: IMPLEMENTED,
  },
  {
    id: "tab.newAgent.aider",
    title: "New Aider tab",
    group: "Agents",
    scope: "tabs",
    searchKeywords: [
      "shortcut",
      "tab",
      "agent",
      "new",
      "launch",
      "aider",
      "aider",
    ],
    defaultBindings: same([]),
    status: IMPLEMENTED,
  },
  {
    id: "tab.newAgent.goose",
    title: "New Goose tab",
    group: "Agents",
    scope: "tabs",
    searchKeywords: [
      "shortcut",
      "tab",
      "agent",
      "new",
      "launch",
      "goose",
      "goose",
    ],
    defaultBindings: same([]),
    status: IMPLEMENTED,
  },
  {
    id: "tab.newAgent.amp",
    title: "New Amp tab",
    group: "Agents",
    scope: "tabs",
    searchKeywords: ["shortcut", "tab", "agent", "new", "launch", "amp", "amp"],
    defaultBindings: same([]),
    status: IMPLEMENTED,
  },
  {
    id: "tab.newAgent.kilo",
    title: "New Kilocode tab",
    group: "Agents",
    scope: "tabs",
    searchKeywords: [
      "shortcut",
      "tab",
      "agent",
      "new",
      "launch",
      "kilo",
      "kilocode",
    ],
    defaultBindings: same([]),
    status: IMPLEMENTED,
  },
  {
    id: "tab.newAgent.kiro",
    title: "New Kiro tab",
    group: "Agents",
    scope: "tabs",
    searchKeywords: [
      "shortcut",
      "tab",
      "agent",
      "new",
      "launch",
      "kiro",
      "kiro",
    ],
    defaultBindings: same([]),
    status: IMPLEMENTED,
  },
  {
    id: "tab.newAgent.crush",
    title: "New Charm tab",
    group: "Agents",
    scope: "tabs",
    searchKeywords: [
      "shortcut",
      "tab",
      "agent",
      "new",
      "launch",
      "crush",
      "charm",
    ],
    defaultBindings: same([]),
    status: IMPLEMENTED,
    },
  {
    id: "tab.newAgent.aug",
    title: "New Auggie tab",
    group: "Agents",
    scope: "tabs",
    searchKeywords: [
      "shortcut",
      "tab",
      "agent",
      "new",
      "launch",
      "aug",
      "auggie",
    ],
    defaultBindings: same([]),
    status: IMPLEMENTED,
  },
  {
    id: "tab.newAgent.cline",
    title: "New Cline tab",
    group: "Agents",
    scope: "tabs",
    searchKeywords: [
      "shortcut",
      "tab",
      "agent",
      "new",
      "launch",
      "cline",
      "cline",
    ],
    defaultBindings: same([]),
    status: IMPLEMENTED,
  },
  {
    id: "tab.newAgent.codebuff",
    title: "New Codebuff tab",
    group: "Agents",
    scope: "tabs",
    searchKeywords: [
      "shortcut",
      "tab",
      "agent",
      "new",
      "launch",
      "codebuff",
      "codebuff",
    ],
    defaultBindings: same([]),
    status: IMPLEMENTED,
  },
  {
    id: "tab.newAgent.command-code",
    title: "New Command Code tab",
    group: "Agents",
    scope: "tabs",
    searchKeywords: [
      "shortcut",
      "tab",
      "agent",
      "new",
      "launch",
      "command-code",
      "command code",
    ],
    defaultBindings: same([]),
    status: IMPLEMENTED,
  },
  {
    id: "tab.newAgent.continue",
    title: "New Continue tab",
    group: "Agents",
    scope: "tabs",
    searchKeywords: [
      "shortcut",
      "tab",
      "agent",
      "new",
      "launch",
      "continue",
      "continue",
    ],
    defaultBindings: same([]),
    status: IMPLEMENTED,
  },
  {
    id: "tab.newAgent.cursor",
    title: "New Cursor tab",
    group: "Agents",
    scope: "tabs",
    searchKeywords: [
      "shortcut",
      "tab",
      "agent",
      "new",
      "launch",
      "cursor",
      "cursor",
    ],
    defaultBindings: same([]),
    status: IMPLEMENTED,
  },
  {
    id: "tab.newAgent.droid",
    title: "New Droid tab",
    group: "Agents",
    scope: "tabs",
    searchKeywords: [
      "shortcut",
      "tab",
      "agent",
      "new",
      "launch",
      "droid",
      "droid",
    ],
    defaultBindings: same([]),
    status: IMPLEMENTED,
  },
  {
    id: "tab.newAgent.kimi",
    title: "New Kimi tab",
    group: "Agents",
    scope: "tabs",
    searchKeywords: [
      "shortcut",
      "tab",
      "agent",
      "new",
      "launch",
      "kimi",
      "kimi",
    ],
    defaultBindings: same([]),
    status: IMPLEMENTED,
  },
  {
    id: "tab.newAgent.mistral-vibe",
    title: "New Mistral Vibe tab",
    group: "Agents",
    scope: "tabs",
    searchKeywords: [
      "shortcut",
      "tab",
      "agent",
      "new",
      "launch",
      "mistral-vibe",
      "mistral vibe",
    ],
    defaultBindings: same([]),
    status: IMPLEMENTED,
  },
  {
    id: "tab.newAgent.qwen-code",
    title: "New Qwen Code tab",
    group: "Agents",
    scope: "tabs",
    searchKeywords: [
      "shortcut",
      "tab",
      "agent",
      "new",
      "launch",
      "qwen-code",
      "qwen code",
    ],
    defaultBindings: same([]),
    status: IMPLEMENTED,
  },
  {
    id: "tab.newAgent.rovo",
    title: "New Rovo Dev tab",
    group: "Agents",
    scope: "tabs",
    searchKeywords: [
      "shortcut",
      "tab",
      "agent",
      "new",
      "launch",
      "rovo",
      "rovo dev",
    ],
    defaultBindings: same([]),
    status: IMPLEMENTED,
  },
  {
    id: "tab.newAgent.hermes",
    title: "New Hermes tab",
    group: "Agents",
    scope: "tabs",
    searchKeywords: [
      "shortcut",
      "tab",
      "agent",
      "new",
      "launch",
      "hermes",
      "hermes",
    ],
    defaultBindings: same([]),
    status: IMPLEMENTED,
  },
  {
    id: "tab.newAgent.openclaw",
    title: "New OpenClaw tab",
    group: "Agents",
    scope: "tabs",
    searchKeywords: [
      "shortcut",
      "tab",
      "agent",
      "new",
      "launch",
      "openclaw",
      "openclaw",
    ],
    defaultBindings: same([]),
    status: IMPLEMENTED,
  },
  {
    id: "tab.newAgent.copilot",
    title: "New GitHub Copilot tab",
    group: "Agents",
    scope: "tabs",
    searchKeywords: [
      "shortcut",
      "tab",
      "agent",
      "new",
      "launch",
      "copilot",
      "github copilot",
    ],
    defaultBindings: same([]),
    status: IMPLEMENTED,
  },
  {
    id: "tab.newAgent.grok",
    title: "New Grok tab",
    group: "Agents",
    scope: "tabs",
    searchKeywords: [
      "shortcut",
      "tab",
      "agent",
      "new",
      "launch",
      "grok",
      "grok",
    ],
    defaultBindings: same([]),
    status: IMPLEMENTED,
  },
];

export const DEFINITIONS_BY_ID = new Map<string, KeybindingDefinition>(
  KEYBINDING_DEFINITIONS.map((definition) => [definition.id, definition]),
);

export function getKeybindingDefinition(
  id: string,
): KeybindingDefinition | null {
  return DEFINITIONS_BY_ID.get(id) ?? null;
}

/** Source group order: first appearance across the definition table. */
export function keybindingGroupOrder(): string[] {
  const order: string[] = [];
  for (const definition of KEYBINDING_DEFINITIONS) {
    if (!order.includes(definition.group)) order.push(definition.group);
  }
  return order;
}

export function bindingsForPlatform(
  definition: KeybindingDefinition,
  platform: KeybindingPlatform,
): readonly string[] {
  return definition.defaultBindings[platform];
}

/** Drogon UI code distinguishes only darwin vs other. */
export function resolveKeybindingPlatform(
  uiPlatform: "darwin" | "other",
): KeybindingPlatform {
  return uiPlatform === "darwin" ? "darwin" : "linux";
}

/** NodeJS.Platform → the table's platform key (source getKeybindingPlatform). */
export function getKeybindingPlatform(
  platform: typeof process.platform,
): KeybindingPlatform {
  if (platform === "darwin") return "darwin";
  if (platform === "win32") return "win32";
  return "linux";
}

export function isDigitIndexDefinition(
  definition: KeybindingDefinition,
): boolean {
  return definition.digitIndex === true;
}
